import { requirePermission } from "@/lib/admin/auth";
import { getPaymentIntegrationStatus } from "@/lib/commerce/providers/config";

export default async function PaymentSettingsPage() {
  await requirePermission("settings.read");
  const integration = getPaymentIntegrationStatus();
  return <IntegrationSettings title="支付配置" eyebrow="数据与系统" description="支付凭据仅能在 Vercel Environment Variables 中配置；后台只显示连接状态和缺失变量，不读取或展示密钥。" integration={integration} steps={["在 Vercel 为 Production 与 Preview 分别录入服务商变量。", "将服务商回调地址设置为下方 Webhook 地址，并确认签名算法与事件 ID 请求头。", "提供服务商 API 文档后，启用创建支付链接、支付状态映射与退款接口。"]}/>;
}

function IntegrationSettings({ title, eyebrow, description, integration, steps }: { title: string; eyebrow: string; description: string; integration: { provider: string; configured: boolean; missing: string[]; webhookPath: string }; steps: string[] }) { return <div className="mx-auto max-w-5xl px-5 py-7 sm:px-8 lg:px-10"><div className="border-b border-black/10 pb-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#538a42]">{eyebrow}</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-[-0.04em]">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-black/55">{description}</p></div><section className="mt-6 rounded-2xl border border-black/10 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-black/50">当前 Provider</p><h2 className="mt-1 text-xl font-bold">{integration.provider}</h2></div><span className={`rounded-full px-3 py-1.5 text-sm font-bold ${integration.configured ? "bg-[#edf4e9] text-[#3e752e]" : "bg-[#fff4df] text-[#9a5a00]"}`}>{integration.configured ? "已配置，待服务商联调" : "暂未完成配置"}</span></div><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-xl bg-[#f6f7f5] p-5"><h3 className="font-bold">Webhook 地址</h3><code className="mt-3 block break-all rounded-lg bg-[#17231c] p-3 text-sm text-white">https://cowinglasses.com{integration.webhookPath}</code><p className="mt-3 text-sm leading-6 text-black/55">回调请求必须携带 <code>x-cowin-signature</code>（HMAC-SHA256 原始请求体）和 <code>x-provider-event-id</code>，重复事件会被幂等忽略。</p></div><div className="rounded-xl border border-dashed border-black/15 p-5"><h3 className="font-bold">缺失环境变量</h3>{integration.missing.length ? <ul className="mt-3 grid gap-2 font-mono text-xs text-black/65">{integration.missing.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-3 text-sm text-[#3e752e]">变量已满足基础接入条件。</p>}</div></div><div className="mt-6 border-t border-black/10 pt-5"><h3 className="font-bold">接入步骤</h3><ol className="mt-3 grid gap-2 text-sm leading-6 text-black/60">{steps.map((step, index) => <li key={step}>{index + 1}. {step}</li>)}</ol></div></section></div>; }
