"use client";

import { useActionState } from "react";
import { createProductAction, initialProductFormState } from "@/app/admin/(console)/products/actions";

export function ProductCreateForm() {
  const [state, action, pending] = useActionState(createProductAction, initialProductFormState);
  return <form action={action} className="mt-7 grid gap-5 rounded-2xl border border-black/10 bg-white p-6 shadow-[0_10px_30px_rgba(15,25,19,0.04)] md:grid-cols-2"><label className="text-sm font-semibold">商品名称<input required name="name" className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5 outline-none focus:border-[#548544] focus:ring-2 focus:ring-[#b8e629]/30" /></label><label className="text-sm font-semibold">商品 Slug<input required name="slug" placeholder="g200-sport-audio-glasses" className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5 outline-none focus:border-[#548544] focus:ring-2 focus:ring-[#b8e629]/30" /></label><label className="text-sm font-semibold">SKU<input required name="sku" placeholder="G200-BLUE" className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5 outline-none focus:border-[#548544] focus:ring-2 focus:ring-[#b8e629]/30" /></label><label className="text-sm font-semibold">销售价（USD）<input required name="price" inputMode="decimal" placeholder="52.00" className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5 outline-none focus:border-[#548544] focus:ring-2 focus:ring-[#b8e629]/30" /></label><label className="text-sm font-semibold">初始库存<input required name="inventory" type="number" min="0" defaultValue="0" className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5 outline-none focus:border-[#548544] focus:ring-2 focus:ring-[#b8e629]/30" /></label><label className="text-sm font-semibold">状态<select name="status" defaultValue="draft" className="mt-2 w-full rounded-xl border border-black/12 bg-white px-3 py-2.5 outline-none focus:border-[#548544]"><option value="draft">草稿</option><option value="active">上架</option></select></label><label className="md:col-span-2 text-sm font-semibold">商品描述<textarea name="description" rows={5} className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5 outline-none focus:border-[#548544] focus:ring-2 focus:ring-[#b8e629]/30" /></label><div className="md:col-span-2 rounded-xl bg-[#f5f7f4] p-4 text-sm text-black/55">图片上传、分类、品牌、规格选项和 SEO 会在媒体库与商品编辑器接入后补充；未配置对象存储前不会显示伪造上传功能。</div>{state.message ? <p role="status" className={`md:col-span-2 rounded-xl px-4 py-3 text-sm ${state.success ? "bg-[#eef8e8] text-[#376c2a]" : "bg-red-50 text-red-700"}`}>{state.message}</p> : null}<div className="md:col-span-2 flex justify-end gap-3"><button type="submit" disabled={pending} className="rounded-xl bg-[#17231c] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在创建…" : "创建商品"}</button></div></form>;
}
