import Link from "next/link";
import { and, count, desc, eq, gte, ilike, lte, or } from "drizzle-orm";
import { DateRangeFilter } from "@/components/admin/date-range-filter";
import { TablePagination } from "@/components/admin/table-pagination";
import { getDatabase } from "@/db/client";
import { orders, shipments } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";
import { dateRangeQuery, getDateRange } from "@/lib/admin/date-range";
import { ADMIN_PAGE_SIZES, getAdminPagination } from "@/lib/admin/pagination";

type Search = { range?: string; from?: string; to?: string; page?: string; pageSize?: string; q?: string; status?: string };
const shipmentStatuses = ["processing", "partially_shipped", "shipped", "delivered", "unfulfilled", "exception"] as const;

export default async function FulfillmentPage({ searchParams }: { searchParams: Promise<Search> }) {
  await requirePermission("orders.read");
  const input = await searchParams; const range = getDateRange(input); const { page, pageSize, offset } = getAdminPagination(input, 50); const q = input.q?.trim() ?? ""; const status = shipmentStatuses.includes(input.status as (typeof shipmentStatuses)[number]) ? input.status as (typeof shipmentStatuses)[number] : undefined;
  const where = and(gte(shipments.createdAt, range.from), lte(shipments.createdAt, range.to), status ? eq(shipments.status, status) : undefined, q ? or(ilike(orders.orderNumber, `%${q}%`), ilike(shipments.trackingNumber, `%${q}%`), ilike(shipments.provider, `%${q}%`)) : undefined);
  const db = getDatabase(); const [{ total }] = await db.select({ total: count() }).from(shipments).innerJoin(orders, eq(shipments.orderId, orders.id)).where(where);
  const rows = await db.select({ id: shipments.id, provider: shipments.provider, tracking: shipments.trackingNumber, status: shipments.status, shippedAt: shipments.shippedAt, deliveredAt: shipments.deliveredAt, createdAt: shipments.createdAt, orderId: orders.id, orderNumber: orders.orderNumber }).from(shipments).innerJoin(orders, eq(shipments.orderId, orders.id)).where(where).orderBy(desc(shipments.createdAt)).limit(pageSize).offset(offset);
  const href = (nextPage: number) => `/admin/fulfillment?${new URLSearchParams({ ...dateRangeQuery(range), ...(q ? { q } : {}), ...(status ? { status } : {}), pageSize: String(pageSize), page: String(nextPage) })}`;
  return <div className="mx-auto max-w-[1560px] px-5 py-7 sm:px-8 lg:px-10"><div className="flex items-end justify-between border-b border-black/10 pb-7"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#538a42]">经营</p><h1 className="mt-2 font-serif text-4xl font-bold">发货与物流</h1><p className="mt-2 text-sm text-black/55">按真实发货时间、状态、订单和物流单号查询服务端物流记录。</p></div><Link href="/admin/settings/logistics" className="rounded-xl border border-black/15 px-4 py-2.5 text-sm font-bold">物流配置</Link></div><form className="mt-6 rounded-2xl border border-black/10 bg-white p-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_160px_150px]"><input name="q" defaultValue={q} placeholder="订单号、物流单号或承运商" className="rounded-xl border border-black/12 px-3 py-2.5"/><input name="status" defaultValue={status} placeholder="物流状态" className="rounded-xl border border-black/12 px-3 py-2.5"/><label className="grid gap-1 text-xs font-semibold text-black/60">每页条数<select name="pageSize" defaultValue={pageSize} className="rounded-xl border border-black/12 bg-white px-3 py-2.5">{ADMIN_PAGE_SIZES.map((size) => <option key={size} value={size}>{size} 条</option>)}</select></label></div><DateRangeFilter range={range} className="mt-3"/><button className="mt-3 rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white">查询物流</button></form><section className="mt-5 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-[#f5f7f4] text-xs uppercase tracking-wide text-black/52"><tr><th className="px-5 py-4">订单</th><th className="px-5 py-4">物流 Provider</th><th className="px-5 py-4">物流单号</th><th className="px-5 py-4">状态</th><th className="px-5 py-4">发货时间</th><th className="px-5 py-4">送达时间</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-black/8"><td className="px-5 py-4"><Link href={`/admin/orders/${row.orderId}`} className="font-bold text-[#477b38]">{row.orderNumber}</Link></td><td className="px-5 py-4">{row.provider ?? "—"}</td><td className="px-5 py-4 font-mono text-xs">{row.tracking ?? "—"}</td><td className="px-5 py-4">{row.status}</td><td className="px-5 py-4 text-black/55">{row.shippedAt?.toLocaleString("zh-CN") ?? "—"}</td><td className="px-5 py-4 text-black/55">{row.deliveredAt?.toLocaleString("zh-CN") ?? "—"}</td></tr>) : <tr><td colSpan={6} className="px-5 py-14 text-center text-black/55">当前筛选条件下暂无发货记录。</td></tr>}</tbody></table></div><TablePagination page={page} pageSize={pageSize} total={Number(total)} href={href}/></section></div>;
}
