"use server";

import { revalidatePath } from "next/cache";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { getDatabase } from "@/db/client";
import { brands, categories, suppliers } from "@/db/schema";
import { writeAuditLog } from "@/lib/admin/audit";
import { requirePermission } from "@/lib/admin/auth";

export type CatalogFormState = { success: boolean; message: string };
export const initialCatalogFormState: CatalogFormState = { success: false, message: "" };
const slug = z.string().trim().min(2, "请填写至少 2 个字符的 Slug。").max(180).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Slug 仅支持小写英文、数字和连字符。");
const categorySchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(160), slug, description: z.string().trim().max(2000).optional(), sortOrder: z.coerce.number().int().min(0).max(100000), isActive: z.enum(["true", "false"]).default("true") });
const brandSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(160), slug, description: z.string().trim().max(2000).optional(), logoUrl: z.union([z.literal(""), z.string().url("Logo 地址格式不正确。")]), isActive: z.enum(["true", "false"]).default("true") });
const supplierSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(160), contactName: z.string().trim().max(160).optional(), email: z.union([z.literal(""), z.string().email("邮箱格式不正确。")]), phone: z.string().trim().max(64).optional(), address: z.string().trim().max(1000).optional(), notes: z.string().trim().max(4000).optional(), isActive: z.enum(["true", "false"]).default("true") });

function state<T>(schema: z.ZodType<T>, formData: FormData) { const result = schema.safeParse(Object.fromEntries(formData)); return result.success ? { value: result.data } : { error: result.error.issues[0]?.message ?? "输入不完整。" }; }
async function finalize(actorId: string, action: string, resourceType: string, resourceId: string | undefined, result: "success" | "failure", pathname: string) { await writeAuditLog({ actorId, action, resourceType, resourceId, result }); revalidatePath(pathname); revalidatePath("/admin/products"); }

export async function saveCategoryAction(_state: CatalogFormState, formData: FormData): Promise<CatalogFormState> { const actor = await requirePermission("catalog.update"); const parsed = state(categorySchema, formData); if ("error" in parsed) return { success: false, message: parsed.error ?? "输入不完整。" }; try { const value = parsed.value; let id = value.id; if (id) await getDatabase().update(categories).set({ name: value.name, slug: value.slug, description: value.description || null, sortOrder: value.sortOrder, isActive: value.isActive === "true", updatedAt: new Date() }).where(eq(categories.id, id)); else { const [created] = await getDatabase().insert(categories).values({ name: value.name, slug: value.slug, description: value.description || null, sortOrder: value.sortOrder, isActive: value.isActive === "true" }).returning({ id: categories.id }); id = created?.id; } await finalize(actor.id, `catalog.category.${value.id ? "update" : "create"}`, "category", id, "success", "/admin/categories"); return { success: true, message: value.id ? "分类已更新。" : "分类已创建。" }; } catch (error) { console.error("保存分类失败", error); await finalize(actor.id, "catalog.category.save", "category", undefined, "failure", "/admin/categories"); return { success: false, message: "保存失败，请确认名称和 Slug 未重复。" }; } }
export async function saveBrandAction(_state: CatalogFormState, formData: FormData): Promise<CatalogFormState> { const actor = await requirePermission("catalog.update"); const parsed = state(brandSchema, formData); if ("error" in parsed) return { success: false, message: parsed.error ?? "输入不完整。" }; try { const value = parsed.value; let id = value.id; if (id) await getDatabase().update(brands).set({ name: value.name, slug: value.slug, description: value.description || null, logoUrl: value.logoUrl || null, isActive: value.isActive === "true", updatedAt: new Date() }).where(eq(brands.id, id)); else { const [created] = await getDatabase().insert(brands).values({ name: value.name, slug: value.slug, description: value.description || null, logoUrl: value.logoUrl || null, isActive: value.isActive === "true" }).returning({ id: brands.id }); id = created?.id; } await finalize(actor.id, `catalog.brand.${value.id ? "update" : "create"}`, "brand", id, "success", "/admin/brands"); return { success: true, message: value.id ? "品牌已更新。" : "品牌已创建。" }; } catch (error) { console.error("保存品牌失败", error); await finalize(actor.id, "catalog.brand.save", "brand", undefined, "failure", "/admin/brands"); return { success: false, message: "保存失败，请确认名称和 Slug 未重复。" }; } }
export async function saveSupplierAction(_state: CatalogFormState, formData: FormData): Promise<CatalogFormState> { const actor = await requirePermission("catalog.update"); const parsed = state(supplierSchema, formData); if ("error" in parsed) return { success: false, message: parsed.error ?? "输入不完整。" }; try { const value = parsed.value; let id = value.id; if (id) await getDatabase().update(suppliers).set({ name: value.name, contactName: value.contactName || null, email: value.email || null, phone: value.phone || null, address: value.address || null, notes: value.notes || null, isActive: value.isActive === "true", updatedAt: new Date() }).where(eq(suppliers.id, id)); else { const [created] = await getDatabase().insert(suppliers).values({ name: value.name, contactName: value.contactName || null, email: value.email || null, phone: value.phone || null, address: value.address || null, notes: value.notes || null, isActive: value.isActive === "true" }).returning({ id: suppliers.id }); id = created?.id; } await finalize(actor.id, `catalog.supplier.${value.id ? "update" : "create"}`, "supplier", id, "success", "/admin/suppliers"); return { success: true, message: value.id ? "供应商已更新。" : "供应商已创建。" }; } catch (error) { console.error("保存供应商失败", error); await finalize(actor.id, "catalog.supplier.save", "supplier", undefined, "failure", "/admin/suppliers"); return { success: false, message: "保存失败，请检查供应商资料。" }; } }

export async function deleteCatalogRecordAction(kind: "category" | "brand" | "supplier", id: string) { const actor = await requirePermission("catalog.delete"); if (!z.string().uuid().safeParse(id).success) return; const table = kind === "category" ? categories : kind === "brand" ? brands : suppliers; await getDatabase().delete(table).where(eq(table.id, id)); const pathname = `/admin/${kind === "category" ? "categories" : `${kind}s`}`; await finalize(actor.id, `catalog.${kind}.delete`, kind, id, "success", pathname); }
