"use client";

import { useActionState } from "react";
import { initialOrderUpdateState, updateOrderStatusAction } from "../actions";

type Props = { orderId: string; status: string; paymentStatus: string; fulfillmentStatus: string };
export function OrderStatusForm({ orderId, status, paymentStatus, fulfillmentStatus }: Props) {
  const [state, action, pending] = useActionState(updateOrderStatusAction, initialOrderUpdateState);
  return <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="font-bold">订单状态处理</h2><p className="mt-2 text-sm leading-6 text-black/55">仅后台有“编辑订单”权限的人员可保存。支付渠道未接入前，请勿将订单手动标记为已付款。</p><form action={action} className="mt-4 grid gap-3"><input type="hidden" name="orderId" value={orderId}/><label className="grid gap-1.5 text-sm font-semibold">订单状态<select name="status" defaultValue={status} className="rounded-xl border border-black/12 bg-white px-3 py-2.5"><option value="pending_payment">待付款确认</option><option value="paid">已付款</option><option value="processing">处理中</option><option value="partially_shipped">部分发货</option><option value="shipped">已发货</option><option value="delivered">已送达</option><option value="cancelled">已取消</option><option value="refunded">已退款</option><option value="closed">已关闭</option></select></label><label className="grid gap-1.5 text-sm font-semibold">支付状态<select name="paymentStatus" defaultValue={paymentStatus} className="rounded-xl border border-black/12 bg-white px-3 py-2.5"><option value="pending">待支付</option><option value="authorized">已授权</option><option value="paid">已付款</option><option value="failed">失败</option><option value="cancelled">已取消</option><option value="partially_refunded">部分退款</option><option value="refunded">已退款</option></select></label><label className="grid gap-1.5 text-sm font-semibold">发货状态<select name="fulfillmentStatus" defaultValue={fulfillmentStatus} className="rounded-xl border border-black/12 bg-white px-3 py-2.5"><option value="unfulfilled">未发货</option><option value="processing">处理中</option><option value="partially_shipped">部分发货</option><option value="shipped">已发货</option><option value="delivered">已送达</option><option value="exception">异常</option></select></label>{state.message && <p role="status" className={`rounded-xl p-3 text-sm ${state.success ? "bg-[#edf4e9] text-[#356a2a]" : "bg-red-50 text-red-800"}`}>{state.message}</p>}<button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-3 text-sm font-bold text-white disabled:opacity-55">{pending ? "保存中…" : "保存订单状态"}</button></form></section>;
}
