import type { Locale } from "@/types/localization";

type EditorialChromeKey = "by" | "keyTakeaways" | "originalSource" | "viewSource" | "disclaimer";
export type Messages = Omit<typeof en, "editorial"> & { editorial: Omit<typeof en.editorial, EditorialChromeKey> & Partial<Pick<typeof en.editorial, EditorialChromeKey>> };

const en = {
  nav: { shop: "Shop", explore: "Explore", howItWorks: "How It Works", lensGuide: "Lens Guide", support: "Support", more: "More", contact: "Contact Us", news: "News", blog: "Blog", search: "Search", cart: "Cart", account: "Account" },
  announcement: "Global delivery · Dispatches within 3 business days · 30-day returns",
  common: { shopNow: "Shop now", learnMore: "Learn more", viewAll: "View all", addToCart: "Add to cart", added: "Added to cart", compare: "Compare models", demo: "Available now", estimated: "Estimated local price", finalUsd: "Final payment is charged in USD.", exchange: "Exchange rates are refreshed daily and your card issuer may apply its own rate.", lastUpdated: "Last updated", shipping: "Shipping", returns: "Returns", warranty: "Warranty", searchPlaceholder: "Search frames and features", noResults: "No products matched those filters.", clear: "Clear filters", chooseColor: "Choose a color", quantity: "Quantity", remove: "Remove", continueShopping: "Continue shopping", checkout: "Checkout", submit: "Submit", required: "Required", draft: "Draft - pending legal review", back: "Back", app: "App" },
  home: { title: "Smart eyewear for music, moments, and movement.", intro: "Two approachable ways to start wearing your day differently.", choose: "Choose your CoWin", music: "Music & Movement", capture: "Capture & Translation", flagship: "Flagship capability, considered.", scenarios: "Create, explore, or make everyday lighter.", appTitle: "Your phone keeps the connection moving.", appCopy: "Pair with Bluetooth, manage settings in the CoWin app, and keep translation connected through your phone's internet.", lensTitle: "Prescription-ready, on your terms.", trust: "Community notes", trustCopy: "Customer feedback will be added as it becomes available.", subscribe: "Stay in the frame", subscribeCopy: "Product news and launch updates." },
  product: { dispatch: "In stock. Dispatches within 3 business days.", tax: "Import duties and taxes are the customer's responsibility.", camera: "Camera details", translation: "Translation connection", prescription: "Lens fit", specs: "Specifications", box: "In the box", compatibility: "Compatibility", faq: "Product FAQ", related: "Related products", translationCopy: "Translation requires the CoWin app, Bluetooth and your phone's internet connection. Glasses do not connect directly to the internet.", lensLink: "Read the Lens Guide" },
  shop: { title: "Find your frame", intro: "Explore the current CoWin Glasses collection.", filters: "Filters", sort: "Sort", feature: "Features", scenario: "Use case", lens: "Lens", frame: "Frame style", price: "Price", newest: "Featured", lowHigh: "Price: low to high", highLow: "Price: high to low" },
  footer: { product: "Products", help: "Help", legal: "Legal", shipping: "Shipping & Delivery", returns: "Returns & Refunds", privacy: "Privacy Policy", terms: "Terms of Service", intellectualProperty: "Intellectual Property Rights", warranty: "Warranty & Support", contact: "Contact Support", copyright: "© 2026 CoWin Glasses." },
  cart: { title: "Your cart", empty: "Your cart is waiting for a frame.", subtotal: "Subtotal", delivery: "Delivery is calculated after you choose a destination.", checkoutNote: "Secure payment instructions are provided after order confirmation.", orderSummary: "Order summary" },
  checkout: { title: "Checkout", address: "Delivery address", country: "Country / region", payment: "Payment", paymentCopy: "Secure payment instructions are provided after order confirmation. Do not enter card information here.", brazil: "We are unable to ship to Brazil.", review: "Review order" },
  support: { title: "Support that stays close", intro: "Our 24/7 support team aims to reply within 12 hours.", contact: "Contact support", faq: "Frequently asked questions", formSuccess: "Thanks. Your request has been received. Our support team will follow up." },
  editorial: { newsTitle: "CoWin News", newsIntro: "Verified smart-eyewear, connectivity and creator-technology updates with transparent sources and editorial context.", blogTitle: "The CoWin Journal", blogIntro: "Ideas for creating, travelling and moving with smart eyewear.", empty: "No published stories are available yet.", readArticle: "Read article", published: "Published", by: "By", keyTakeaways: "Key takeaways", originalSource: "Original source", viewSource: "View source", disclaimer: "Editorial disclaimer", backToNews: "Back to News", backToBlog: "Back to Blog" },
};

const ar: Messages = { ...en, nav: { shop: "المتجر", explore: "استكشف", howItWorks: "كيف يعمل", lensGuide: "دليل العدسات", support: "الدعم", more: "المزيد", contact: "اتصل بنا", news: "الأخبار", blog: "المدونة", search: "بحث", cart: "السلة", account: "الحساب" }, announcement: "شحن عالمي · إرسال خلال 3 أيام عمل · إرجاع خلال 30 يوماً", common: { ...en.common, shopNow: "تسوق الآن", learnMore: "اعرف المزيد", viewAll: "عرض الكل", addToCart: "أضف إلى السلة", added: "تمت الإضافة", estimated: "السعر المحلي التقديري", finalUsd: "يتم تحصيل الدفعة النهائية بالدولار الأمريكي.", exchange: "يتم تحديث أسعار الصرف يومياً وقد يطبق مصدر البطاقة سعراً خاصاً.", chooseColor: "اختر اللون", quantity: "الكمية", remove: "إزالة", checkout: "إتمام الطلب", submit: "إرسال", draft: "مسودة - بانتظار المراجعة القانونية" }, home: { ...en.home, title: "نظارات ذكية للموسيقى واللحظات والحركة.", intro: "طريقتان بسيطتان لارتداء يومك بشكل مختلف.", choose: "اختر CoWin المناسب لك", music: "الموسيقى والحركة", capture: "التصوير والترجمة", flagship: "قدرات رائدة بتصميم مدروس.", scenarios: "أنشئ واستكشف واجعل اليوم أخف.", appTitle: "هاتفك يحافظ على الاتصال.", appCopy: "اتصل بالبلوتوث وأدر الإعدادات عبر تطبيق CoWin، وتبقى الترجمة متصلة عبر إنترنت الهاتف.", lensTitle: "جاهزة للعدسات الطبية بشروطك.", trust: "ملاحظات الوصول المبكر", trustCopy: "آراء تجريبية. استبدلها بتقييمات موثقة قبل الإطلاق.", subscribe: "ابق في الإطار", subscribeCopy: "أخبار المنتجات وتحديثات الإطلاق. اشتراك تجريبي فقط." }, editorial: { newsTitle: "أخبار CoWin", newsIntro: "إعلانات المنتجات وتحديثات الشركة والإشعارات المهمة من CoWin Glasses.", blogTitle: "مجلة CoWin", blogIntro: "أفكار للإبداع والسفر والحركة بالنظارات الذكية.", empty: "لا توجد قصص منشورة بعد.", readArticle: "اقرأ المقال", published: "نُشر", backToNews: "العودة إلى الأخبار", backToBlog: "العودة إلى المدونة" } };
const es: Messages = { ...en, nav: { shop: "Tienda", explore: "Explorar", howItWorks: "Cómo funciona", lensGuide: "Guía de lentes", support: "Soporte", more: "Más", contact: "Contáctanos", news: "Noticias", blog: "Blog", search: "Buscar", cart: "Carrito", account: "Cuenta" }, announcement: "Envío global · Despacho en 3 días hábiles · Devoluciones de 30 días", common: { ...en.common, shopNow: "Comprar", learnMore: "Más información", addToCart: "Añadir al carrito", estimated: "Precio local estimado", finalUsd: "El pago final se cobra en USD.", draft: "Borrador - pendiente de revisión legal" }, home: { ...en.home, title: "Gafas inteligentes para música, momentos y movimiento.", intro: "Dos formas accesibles de llevar tu día de otra manera.", choose: "Elige tu CoWin", music: "Música y movimiento", capture: "Captura y traducción", flagship: "Capacidad insignia, bien pensada.", scenarios: "Crea, explora o haz el día más ligero.", appTitle: "Tu teléfono mantiene la conexión.", appCopy: "Conecta por Bluetooth, gestiona ajustes en la app CoWin y usa la conexión de tu teléfono para la traducción.", lensTitle: "Preparadas para graduación, a tu manera.", trust: "Notas de acceso anticipado", trustCopy: "Testimonios de ejemplo. Sustituir por reseñas verificadas antes del lanzamiento.", subscribe: "Mantente en el marco", subscribeCopy: "Noticias de producto y lanzamiento. Registro de demostración." }, editorial: { newsTitle: "Noticias de CoWin", newsIntro: "Anuncios de productos, novedades de la empresa y avisos importantes de CoWin Glasses.", blogTitle: "Diario CoWin", blogIntro: "Ideas para crear, viajar y moverse con gafas inteligentes.", empty: "Todavía no hay historias publicadas.", readArticle: "Leer artículo", published: "Publicado", backToNews: "Volver a Noticias", backToBlog: "Volver al Blog" } };
const pt: Messages = { ...en, nav: { shop: "Loja", explore: "Explorar", howItWorks: "Como funciona", lensGuide: "Guia de lentes", support: "Suporte", more: "Mais", contact: "Fale conosco", news: "Notícias", blog: "Blog", search: "Buscar", cart: "Carrinho", account: "Conta" }, announcement: "Entrega global · Envio em até 3 dias úteis · Devoluções em 30 dias", common: { ...en.common, shopNow: "Comprar", learnMore: "Saiba mais", addToCart: "Adicionar ao carrinho", estimated: "Preço local estimado", finalUsd: "O pagamento final é cobrado em USD.", draft: "Rascunho - pendente de revisão jurídica" }, home: { ...en.home, title: "Óculos inteligentes para música, momentos e movimento.", intro: "Duas formas acessíveis de usar o seu dia de um jeito diferente.", choose: "Escolha seu CoWin", music: "Música e movimento", capture: "Captura e tradução", flagship: "Capacidade principal, bem pensada.", scenarios: "Crie, explore ou torne o cotidiano mais leve.", appTitle: "Seu telefone mantém a conexão.", appCopy: "Emparelhe por Bluetooth, controle ajustes no app CoWin e use a internet do telefone para tradução.", lensTitle: "Pronto para lentes de grau, do seu jeito.", trust: "Notas de acesso antecipado", trustCopy: "Depoimentos de exemplo. Substitua por avaliações verificadas antes do lançamento.", subscribe: "Fique no enquadramento", subscribeCopy: "Notícias de produtos e lançamento. Cadastro de demonstração." }, editorial: { newsTitle: "Notícias CoWin", newsIntro: "Anúncios de produtos, novidades da empresa e avisos importantes da CoWin Glasses.", blogTitle: "Diário CoWin", blogIntro: "Ideias para criar, viajar e se movimentar com óculos inteligentes.", empty: "Ainda não há histórias publicadas.", readArticle: "Ler artigo", published: "Publicado", backToNews: "Voltar para Notícias", backToBlog: "Voltar para o Blog" } };
const ja: Messages = { ...en, nav: { shop: "ショップ", explore: "探す", howItWorks: "使い方", lensGuide: "レンズガイド", support: "サポート", more: "その他", contact: "お問い合わせ", news: "ニュース", blog: "ブログ", search: "検索", cart: "カート", account: "アカウント" }, announcement: "世界配送 · 3営業日以内に発送 · 30日間返品", common: { ...en.common, shopNow: "購入する", learnMore: "詳しく見る", addToCart: "カートに追加", estimated: "現地通貨の参考価格", finalUsd: "最終決済は米ドルで請求されます。", draft: "ドラフト - 法務レビュー待ち" }, home: { ...en.home, title: "音楽、瞬間、動きのためのスマートアイウェア。", intro: "毎日の過ごし方を変える、2つの始めやすい選択肢。", choose: "CoWinを選ぶ", music: "音楽とアクティブ", capture: "撮影と翻訳", flagship: "考え抜かれたフラッグシップ機能。", scenarios: "つくる、探検する、毎日を軽くする。", appTitle: "スマートフォンが接続を保ちます。", appCopy: "Bluetoothでペアリングし、CoWinアプリで設定を管理。翻訳はスマートフォンのインターネット接続を使用します。", lensTitle: "自分らしい度付きレンズ対応。", trust: "アーリーアクセスの声", trustCopy: "プレースホルダーのレビューです。発売前に確認済みレビューへ置き換えてください。", subscribe: "最新情報を受け取る", subscribeCopy: "製品ニュースと発売情報。デモ登録のみ。" }, editorial: { newsTitle: "CoWinニュース", newsIntro: "CoWin Glassesの製品発表、企業ニュース、重要なお知らせ。", blogTitle: "CoWinジャーナル", blogIntro: "スマートアイウェアと創作、旅、アクティブライフのアイデア。", empty: "公開されている記事はまだありません。", readArticle: "記事を読む", published: "公開日", backToNews: "ニュースへ戻る", backToBlog: "ブログへ戻る" } };
const ko: Messages = { ...en, nav: { shop: "스토어", explore: "탐색", howItWorks: "작동 방식", lensGuide: "렌즈 가이드", support: "지원", more: "더보기", contact: "문의하기", news: "뉴스", blog: "블로그", search: "검색", cart: "장바구니", account: "계정" }, announcement: "글로벌 배송 · 영업일 기준 3일 내 발송 · 30일 반품", common: { ...en.common, shopNow: "쇼핑하기", learnMore: "자세히 보기", addToCart: "장바구니 담기", estimated: "현지 통화 예상 가격", finalUsd: "최종 결제는 USD로 청구됩니다.", draft: "초안 - 법률 검토 대기 중" }, home: { ...en.home, title: "음악, 순간, 움직임을 위한 스마트 아이웨어.", intro: "일상을 다르게 착용하는 두 가지 부담 없는 방법.", choose: "나의 CoWin 선택", music: "음악과 움직임", capture: "캡처와 번역", flagship: "섬세하게 완성한 플래그십 역량.", scenarios: "창작하고, 탐험하고, 일상을 가볍게 만드세요.", appTitle: "휴대폰이 연결을 이어 줍니다.", appCopy: "Bluetooth로 연결하고 CoWin 앱에서 설정을 관리하세요. 번역은 휴대폰 인터넷 연결을 사용합니다.", lensTitle: "나만의 방식으로 도수 렌즈 준비.", trust: "얼리 액세스 후기", trustCopy: "자리표시자 후기입니다. 출시 전 검증된 고객 후기와 교체하세요.", subscribe: "프레임 안에 머무르세요", subscribeCopy: "제품 소식과 출시 업데이트. 데모 구독만 지원합니다." }, editorial: { newsTitle: "CoWin 뉴스", newsIntro: "CoWin Glasses의 제품 발표, 회사 소식 및 중요 공지입니다.", blogTitle: "CoWin 저널", blogIntro: "스마트 아이웨어와 함께 만드는 창작, 여행, 움직임의 아이디어입니다.", empty: "아직 게시된 이야기가 없습니다.", readArticle: "글 읽기", published: "게시일", backToNews: "뉴스로 돌아가기", backToBlog: "블로그로 돌아가기" } };

export const messages: Record<Locale, Messages> = { en, ar, es, pt, ja, ko };

export const editorialArticleLabels: Record<Locale, Pick<typeof en.editorial, EditorialChromeKey>> = {
  en: { by: "By", keyTakeaways: "Key takeaways", originalSource: "Original source", viewSource: "View source", disclaimer: "Editorial disclaimer" },
  ar: { by: "بقلم", keyTakeaways: "أهم النقاط", originalSource: "المصدر الأصلي", viewSource: "عرض المصدر", disclaimer: "إخلاء مسؤولية تحريري" },
  es: { by: "Por", keyTakeaways: "Puntos clave", originalSource: "Fuente original", viewSource: "Ver fuente", disclaimer: "Aviso editorial" },
  pt: { by: "Por", keyTakeaways: "Principais conclusões", originalSource: "Fonte original", viewSource: "Ver fonte", disclaimer: "Aviso editorial" },
  ja: { by: "執筆", keyTakeaways: "要点", originalSource: "一次情報", viewSource: "出典を見る", disclaimer: "編集上の注記" },
  ko: { by: "작성", keyTakeaways: "핵심 요약", originalSource: "원문 출처", viewSource: "출처 보기", disclaimer: "편집 고지" },
};
