"use server";
import { revalidatePath } from "next/cache";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { getDatabase } from "@/db/client";
import { coupons, promotions } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";
import { writeAuditLog } from "@/lib/admin/audit";
export type MarketingState = { success: boolean; message: string };
export const initialMarketingState: MarketingState = { success: false, message: "" };
const couponSchema = z.object({ id: z.string().uuid().optional(), code: z.string().trim().min(2).max(80).regex(/^[A-Z0-9_-]+$/, "优惠码仅支持大写字母、数字、下划线和连字符。"), discountType: z.enum(["percentage", "fixed"]), discountValue: z.string().regex(/^\d+(\.\d{1,2})?$/), minimumAmount: z.union([z.literal(""), z.string().regex(/^\d+(\.\d{1,2})?$/)]), usageLimit: z.union([z.literal(""), z.coerce.number().int().min(1).max(1000000)]), isActive: z.enum(["true", "false"]) });
const promoSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(160), type: z.enum(["percentage", "fixed", "free_shipping"]), rules: z.string().trim().max(4000).optional(), isActive: z.enum(["true", "false"]) });
async function complete(actorId: string, action: string, type: string, id: string | undefined, success: boolean) { await writeAuditLog({ actorId, action, resourceType: type, resourceId: id, result: success ? "success" : "failure" }); revalidatePath("/admin/promotions"); }
export async function saveCouponAction(_state: MarketingState, fd: FormData): Promise<MarketingState> { const actor = await requirePermission("catalog.update"); const parsed = couponSchema.safeParse(Object.fromEntries(fd)); if (!parsed.success) return { success: false, message: parsed.error.issues[0]?.message ?? "优惠码信息不完整。" }; const v = parsed.data; try { let id = v.id; const values = { code: v.code, discountType: v.discountType, discountValue: v.discountValue, minimumAmount: v.minimumAmount || null, usageLimit: v.usageLimit === "" ? null : v.usageLimit, isActive: v.isActive === "true", updatedAt: new Date() }; if (id) await getDatabase().update(coupons).set(values).where(eq(coupons.id, id)); else { const [created] = await getDatabase().insert(coupons).values(values).returning({ id: coupons.id }); id = created?.id; } await complete(actor.id, `marketing.coupon.${v.id ? "update" : "create"}`, "coupon", id, true); return { success: true, message: v.id ? "优惠码已保存。" : "优惠码已创建。" }; } catch (e) { console.error(e); await complete(actor.id, "marketing.coupon.save", "coupon", undefined, false); return { success: false, message: "保存失败，优惠码可能已重复。" }; } }
export async function savePromotionAction(_state: MarketingState, fd: FormData): Promise<MarketingState> { const actor = await requirePermission("catalog.update"); const parsed = promoSchema.safeParse(Object.fromEntries(fd)); if (!parsed.success) return { success: false, message: parsed.error.issues[0]?.message ?? "促销信息不完整。" }; const v = parsed.data; try { let rules: Record<string, unknown> = {}; if (v.rules) rules = JSON.parse(v.rules) as Record<string, unknown>; let id = v.id; const values = { name: v.name, type: v.type, rules, isActive: v.isActive === "true", updatedAt: new Date() }; if (id) await getDatabase().update(promotions).set(values).where(eq(promotions.id, id)); else { const [created] = await getDatabase().insert(promotions).values(values).returning({ id: promotions.id }); id = created?.id; } await complete(actor.id, `marketing.promotion.${v.id ? "update" : "create"}`, "promotion", id, true); return { success: true, message: v.id ? "促销活动已保存。" : "促销活动已创建。" }; } catch (e) { console.error(e); return { success: false, message: "保存失败；规则必须是有效 JSON。" }; } }
