import Link from "next/link";
import { and, desc, eq, gte, lte } from "drizzle-orm";
import { getDatabase } from "@/db/client";
import { aftersalesRequests, inventoryLevels, orders, products, productSkus, refunds } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";

const day = (offset = 0) => { const value = new Date(); value.setHours(0, 0, 0, 0); value.setDate(value.getDate() + offset); return value; };
const money = (value: number) => value.toLocaleString("en-US", { style: "currency", currency: "USD" });

export async function AdminDashboard() {
  await requirePermission("dashboard.read");
  const db = getDatabase(); const today = day(); const week = day(-6); const month = day(-29);
  const [paid, todayOrders, weekOrders, monthOrders, refundRows, lowStock, aftersales] = await Promise.all([
    db.select({ total: orders.totalAmount, createdAt: orders.createdAt }).from(orders).where(and(eq(orders.paymentStatus, "paid"), gte(orders.createdAt, month))),
    db.select({ id: orders.id }).from(orders).where(gte(orders.createdAt, today)),
    db.select({ id: orders.id }).from(orders).where(gte(orders.createdAt, week)),
    db.select({ total: orders.totalAmount }).from(orders).where(gte(orders.createdAt, month)),
    db.select({ amount: refunds.amount }).from(refunds).where(gte(refunds.createdAt, month)),
    db.select({ sku: productSkus.sku, name: products.name, onHand: inventoryLevels.onHand, reserved: inventoryLevels.reserved, reorderPoint: inventoryLevels.reorderPoint }).from(inventoryLevels).innerJoin(productSkus, eq(inventoryLevels.skuId, productSkus.id)).innerJoin(products, eq(productSkus.productId, products.id)).where(lte(inventoryLevels.onHand, inventoryLevels.reorderPoint)).orderBy(desc(inventoryLevels.updatedAt)).limit(5),
    db.select({ id: aftersalesRequests.id }).from(aftersalesRequests).where(eq(aftersalesRequests.status, "requested")),
  ]);
  const todaySales = paid.filter((row) => row.createdAt >= today).reduce((sum, row) => sum + Number(row.total), 0);
  const monthSales = paid.reduce((sum, row) => sum + Number(row.total), 0);
  const refundsTotal = refundRows.reduce((sum, row) => sum + Number(row.amount), 0);
  const values = [["今日销售额", money(todaySales), "已付款订单"], ["本周订单", String(weekOrders.length), "所有订单请求"], ["本月客单价", money(monthOrders.length ? monthSales / monthOrders.length : 0), "按本月订单计算"], ["本月退款金额", money(refundsTotal), "退款记录"]];
  const trend = Array.from({ length: 7 }, (_, index) => { const start = day(index - 6); const end = day(index - 5); return paid.filter((row) => row.createdAt >= start && row.createdAt < end).reduce((sum, row) => sum + Number(row.total), 0); }); const max = Math.max(...trend, 1);
  return <div className="mx-auto max-w-[1560px] px-5 py-7 sm:px-8 lg:px-10"><div className="flex flex-col gap-5 border-b border-black/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#538a42]">COWIN Glasses 后台</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-[-.04em]">数据概览</h1><p className="mt-2 text-sm text-black/55">订单、库存和售后数据直接来自 Neon。</p></div><Link href="/admin/orders" className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white">查看订单</Link></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{values.map(([title, value, note]) => <article key={title} className="rounded-2xl border border-black/10 bg-white p-5"><p className="text-sm font-semibold text-black/58">{title}</p><p className="mt-4 text-4xl font-bold tracking-[-.05em]">{value}</p><p className="mt-3 text-xs text-black/45">{note}</p></article>)}</div><div className="mt-6 grid gap-5 xl:grid-cols-[1.35fr_.85fr]"><section className="rounded-2xl border border-black/10 bg-white p-6"><h2 className="font-serif text-2xl font-bold">近 7 日已付款销售额</h2><div className="mt-8 flex h-56 items-end gap-3 rounded-xl bg-[#f5f7f4] px-6 pb-7">{trend.map((value, index) => <div className="group flex flex-1 flex-col items-center justify-end gap-2" key={index}><span className="invisible text-[10px] font-bold group-hover:visible">{money(value)}</span><div className="w-full rounded-t-lg bg-[#a6c947]" style={{ height: `${Math.max(4, value / max * 100)}%` }}/><span className="text-[10px] text-black/45">{index === 6 ? "今天" : `${6 - index}天前`}</span></div>)}</div></section><section className="rounded-2xl border border-black/10 bg-white p-6"><h2 className="font-serif text-2xl font-bold">待处理事项</h2><div className="mt-5 grid gap-3"><Card title="库存预警" detail={`${lowStock.length} 个 SKU 低于预警阈值`} href="/admin/inventory"/><Card title="待处理售后" detail={`${aftersales.length} 个申请等待审核`} href="/admin/tickets"/><Card title="今日订单" detail={`${todayOrders.length} 笔订单请求`} href="/admin/orders"/></div></section></div><section className="mt-6 rounded-2xl border border-black/10 bg-white p-6"><div className="flex justify-between"><h2 className="font-serif text-2xl font-bold">库存预警</h2><Link href="/admin/inventory" className="text-sm font-bold text-[#477b38]">库存管理 →</Link></div>{lowStock.length ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{lowStock.map((item) => <div className="rounded-xl bg-[#fff8e9] p-4" key={item.sku}><p className="font-bold">{item.name}</p><p className="mt-1 font-mono text-xs text-black/55">{item.sku}</p><p className="mt-3 text-sm">可用 {item.onHand - item.reserved} / 阈值 {item.reorderPoint}</p></div>)}</div> : <p className="mt-5 rounded-xl bg-[#f5f7f4] p-5 text-sm text-black/55">暂无低于预警阈值的已配置库存。</p>}</section></div>;
}
function Card({ title, detail, href }: { title: string; detail: string; href: string }) { return <div className="rounded-xl border border-black/8 p-4"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-black/52">{detail}</p><Link href={href} className="mt-3 inline-block text-sm font-bold text-[#477b38]">前往处理 →</Link></div>; }
