"use client";

import { useActionState } from "react";
import { deleteCatalogRecordAction, initialCatalogFormState, saveBrandAction, saveCategoryAction, saveSupplierAction } from "@/app/admin/(console)/catalog/actions";

const field = "mt-1 w-full rounded-xl border border-black/12 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#548544]";
function Notice({ message, success }: { message: string; success: boolean }) { return message ? <p role="status" className={`rounded-xl px-3 py-2 text-sm ${success ? "bg-[#eef8e8] text-[#376c2a]" : "bg-red-50 text-red-700"}`}>{message}</p> : null; }
function DeleteButton({ kind, id }: { kind: "category" | "brand" | "supplier"; id: string }) { return <button type="button" onClick={() => { if (window.confirm("确定删除此记录？已关联商品不会被删除，但关联将被解除。")) void deleteCatalogRecordAction(kind, id); }} className="text-xs font-bold text-red-600 underline underline-offset-4">删除</button>; }

export function CategoryForm({ record }: { record?: { id: string; name: string; slug: string; description: string | null; sortOrder: number; isActive: boolean } }) { const [state, action, pending] = useActionState(saveCategoryAction, initialCatalogFormState); return <form action={action} className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5"><input type="hidden" name="id" value={record?.id ?? ""}/><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">分类名称<input required name="name" defaultValue={record?.name} className={field}/></label><label className="text-sm font-semibold">Slug<input required name="slug" defaultValue={record?.slug} placeholder="smart-audio-glasses" className={field}/></label><label className="text-sm font-semibold">排序<input required type="number" min="0" name="sortOrder" defaultValue={record?.sortOrder ?? 0} className={field}/></label><label className="text-sm font-semibold">状态<select name="isActive" defaultValue={String(record?.isActive ?? true)} className={field}><option value="true">启用</option><option value="false">停用</option></select></label></div><label className="text-sm font-semibold">描述<textarea name="description" defaultValue={record?.description ?? ""} rows={3} className={field}/></label><Notice {...state}/><div className="flex justify-between gap-3">{record ? <DeleteButton kind="category" id={record.id}/> : <span/>}<button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在保存…" : record ? "保存分类" : "创建分类"}</button></div></form>; }

export function BrandForm({ record }: { record?: { id: string; name: string; slug: string; description: string | null; logoUrl: string | null; isActive: boolean } }) { const [state, action, pending] = useActionState(saveBrandAction, initialCatalogFormState); return <form action={action} className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5"><input type="hidden" name="id" value={record?.id ?? ""}/><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">品牌名称<input required name="name" defaultValue={record?.name} className={field}/></label><label className="text-sm font-semibold">Slug<input required name="slug" defaultValue={record?.slug} placeholder="cowin" className={field}/></label><label className="text-sm font-semibold">Logo 图片 URL<input type="url" name="logoUrl" defaultValue={record?.logoUrl ?? ""} placeholder="https://…" className={field}/></label><label className="text-sm font-semibold">状态<select name="isActive" defaultValue={String(record?.isActive ?? true)} className={field}><option value="true">启用</option><option value="false">停用</option></select></label></div><label className="text-sm font-semibold">品牌描述<textarea name="description" defaultValue={record?.description ?? ""} rows={3} className={field}/></label><Notice {...state}/><div className="flex justify-between gap-3">{record ? <DeleteButton kind="brand" id={record.id}/> : <span/>}<button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在保存…" : record ? "保存品牌" : "创建品牌"}</button></div></form>; }

export function SupplierForm({ record }: { record?: { id: string; name: string; contactName: string | null; email: string | null; phone: string | null; address: string | null; notes: string | null; isActive: boolean } }) { const [state, action, pending] = useActionState(saveSupplierAction, initialCatalogFormState); return <form action={action} className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5"><input type="hidden" name="id" value={record?.id ?? ""}/><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">供应商名称<input required name="name" defaultValue={record?.name} className={field}/></label><label className="text-sm font-semibold">联系人<input name="contactName" defaultValue={record?.contactName ?? ""} className={field}/></label><label className="text-sm font-semibold">邮箱<input type="email" name="email" defaultValue={record?.email ?? ""} className={field}/></label><label className="text-sm font-semibold">电话<input name="phone" defaultValue={record?.phone ?? ""} className={field}/></label><label className="text-sm font-semibold">状态<select name="isActive" defaultValue={String(record?.isActive ?? true)} className={field}><option value="true">启用</option><option value="false">停用</option></select></label></div><label className="text-sm font-semibold">地址<textarea name="address" defaultValue={record?.address ?? ""} rows={2} className={field}/></label><label className="text-sm font-semibold">备注<textarea name="notes" defaultValue={record?.notes ?? ""} rows={3} className={field}/></label><Notice {...state}/><div className="flex justify-between gap-3">{record ? <DeleteButton kind="supplier" id={record.id}/> : <span/>}<button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在保存…" : record ? "保存供应商" : "创建供应商"}</button></div></form>; }
