"use client";

import { useActionState } from "react";
import { initialContentState, registerMediaAction, saveArticleAction, saveBannerAction } from "@/app/admin/(console)/content/actions";
const input = "mt-1 w-full rounded-xl border border-black/12 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#548544]";
function Notice({ message, success }: { message: string; success: boolean }) { return message ? <p role="status" className={`rounded-xl px-3 py-2 text-sm ${success ? "bg-[#eef8e8] text-[#376c2a]" : "bg-red-50 text-red-700"}`}>{message}</p> : null; }

export function ArticleForm({ type, record }: { type: "news" | "blog"; record?: { id: string; title: string; slug: string; excerpt: string | null; body: string | null; status: "draft" | "scheduled" | "published" | "offline"; seoTitle: string | null; seoDescription: string | null; seoKeywords: string | null } }) { const [state, action, pending] = useActionState(saveArticleAction, initialContentState); return <form action={action} className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5"><input type="hidden" name="id" value={record?.id ?? ""}/><input type="hidden" name="type" value={type}/><label className="text-sm font-semibold">标题<input required name="title" defaultValue={record?.title} className={input}/></label><label className="text-sm font-semibold">Slug<input required name="slug" defaultValue={record?.slug} placeholder="new-product-launch" className={input}/></label><label className="text-sm font-semibold">发布状态<select name="status" defaultValue={record?.status ?? "draft"} className={input}><option value="draft">草稿</option><option value="scheduled">定时发布</option><option value="published">立即发布</option><option value="offline">下线</option></select></label><label className="text-sm font-semibold">摘要<textarea name="excerpt" defaultValue={record?.excerpt ?? ""} rows={2} className={input}/></label><label className="text-sm font-semibold">正文<textarea name="body" defaultValue={record?.body ?? ""} rows={8} className={input}/></label><details className="rounded-xl bg-[#f5f7f4] p-4"><summary className="cursor-pointer text-sm font-bold">SEO 设置</summary><div className="mt-3 grid gap-3"><label className="text-sm font-semibold">SEO 标题<input name="seoTitle" defaultValue={record?.seoTitle ?? ""} className={input}/></label><label className="text-sm font-semibold">SEO 描述<textarea name="seoDescription" defaultValue={record?.seoDescription ?? ""} rows={2} className={input}/></label><label className="text-sm font-semibold">关键词<input name="seoKeywords" defaultValue={record?.seoKeywords ?? ""} className={input}/></label></div></details><Notice {...state}/><button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在保存…" : record ? "保存内容" : "创建内容"}</button></form>; }

export function BannerForm({ record }: { record?: { id: string; name: string; placement: string; imageUrl: string; mobileImageUrl: string | null; targetUrl: string | null; sortOrder: number; isActive: boolean } }) { const [state, action, pending] = useActionState(saveBannerAction, initialContentState); return <form action={action} className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5"><input type="hidden" name="id" value={record?.id ?? ""}/><label className="text-sm font-semibold">名称<input required name="name" defaultValue={record?.name} className={input}/></label><label className="text-sm font-semibold">展示位置<input required name="placement" defaultValue={record?.placement} placeholder="home-hero" className={input}/></label><label className="text-sm font-semibold">桌面端图片 URL<input required type="url" name="imageUrl" defaultValue={record?.imageUrl} className={input}/></label><label className="text-sm font-semibold">移动端图片 URL<input type="url" name="mobileImageUrl" defaultValue={record?.mobileImageUrl ?? ""} className={input}/></label><label className="text-sm font-semibold">跳转 URL<input type="url" name="targetUrl" defaultValue={record?.targetUrl ?? ""} className={input}/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold">排序<input type="number" min="0" name="sortOrder" defaultValue={record?.sortOrder ?? 0} className={input}/></label><label className="text-sm font-semibold">状态<select name="isActive" defaultValue={String(record?.isActive ?? false)} className={input}><option value="true">启用</option><option value="false">停用</option></select></label></div><Notice {...state}/><button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在保存…" : record ? "保存 Banner" : "创建 Banner"}</button></form>; }
export function MediaRegisterForm() { const [state, action, pending] = useActionState(registerMediaAction, initialContentState); return <form action={action} className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5"><label className="text-sm font-semibold">媒体 URL<input required type="url" name="url" placeholder="https://…" className={input}/></label><label className="text-sm font-semibold">替代文本<input name="altText" className={input}/></label><label className="text-sm font-semibold">MIME 类型<input name="mimeType" placeholder="image/webp" className={input}/></label><Notice {...state}/><button disabled={pending} className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{pending ? "正在登记…" : "登记媒体"}</button></form>; }
