"use client";

import { useActionState } from "react";
import { initialSettingsState, saveStoreSettingsAction } from "@/app/admin/(console)/settings/actions";

export function StoreSettingsForm({ value }: { value: { storeName?: string; siteUrl?: string; supportEmail?: string; currency?: string; orderPrefix?: string } }) {
  const [state, action, pending] = useActionState(saveStoreSettingsAction, initialSettingsState);
  return <form action={action} className="mt-6 grid gap-4 rounded-2xl border border-black/10 bg-white p-6 md:grid-cols-2"><label className="text-sm font-semibold">商城名称<input required name="storeName" defaultValue={value.storeName ?? "COWIN Glasses"} className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5"/></label><label className="text-sm font-semibold">站点地址<input required name="siteUrl" type="url" defaultValue={value.siteUrl ?? "https://cowinglasses.com"} className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5"/></label><label className="text-sm font-semibold">客服邮箱<input required name="supportEmail" type="email" defaultValue={value.supportEmail ?? "info@cowinglasses.com"} className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5"/></label><label className="text-sm font-semibold">订单前缀<input required name="orderPrefix" defaultValue={value.orderPrefix ?? "CW"} className="mt-2 w-full rounded-xl border border-black/12 px-3 py-2.5"/></label><label className="text-sm font-semibold">默认币种<input readOnly name="currency" value="USD" className="mt-2 w-full rounded-xl border border-black/12 bg-[#f5f7f4] px-3 py-2.5"/></label><p className="self-end text-xs leading-5 text-black/55">支付、物流和通知密钥不会保存在此处，统一由 Vercel 环境变量安全管理。</p>{state.message ? <p role="status" className={`md:col-span-2 rounded-xl px-3 py-2 text-sm ${state.success ? "bg-[#eef8e8] text-[#376c2a]" : "bg-red-50 text-red-700"}`}>{state.message}</p> : null}<div className="md:col-span-2"><button disabled={pending} className="rounded-xl bg-[#17231c] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending ? "正在保存…" : "保存基础设置"}</button></div></form>;
}
