import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { type Locale } from "@/lib/i18n";
import { messages } from "@/messages";
import { PaymentMethods } from "@/components/compliance/payment-methods";
import { businessDetails } from "@/config/business";

export function Footer({ locale }: { locale: Locale }) { const t = messages[locale]; return <footer className="border-t border-[var(--line)] bg-[var(--dark)] text-white"><div className="shell grid gap-10 py-14 md:grid-cols-[1.4fr_repeat(3,1fr)]"><div><p className="text-2xl font-black tracking-[-.04em]">COWIN<span className="text-[var(--lime)]">.</span></p><p className="mt-4 max-w-xs text-sm leading-6 text-zinc-300">Smart eyewear for music, moments, and movement.</p></div><FooterGroup title={t.footer.product} links={[["Shop", "/shop"], ["Compare", "/compare"], ["How it works", "/how-it-works"], ["App", "/app"]]} locale={locale}/><FooterGroup title={t.footer.help} links={[[t.footer.contact, "/support/contact"], [t.footer.shipping, "/support/shipping-delivery"], [t.footer.returns, "/support/returns-refunds"], [t.footer.warranty, "/support/warranty"]]} locale={locale}/><FooterGroup title={t.footer.legal} links={[[t.footer.privacy, "/policies/privacy"], [t.footer.terms, "/policies/terms"], [t.footer.intellectualProperty, "/policies/intellectual-property"]]} locale={locale}/></div><div className="shell grid gap-6 border-t border-white/15 py-7 md:grid-cols-[1fr_auto] md:items-end"><div className="max-w-3xl text-xs leading-5 text-zinc-400"><p>{businessDetails.legalName}</p><address className="mt-1 not-italic">{businessDetails.registeredAddress}</address><a className="mt-1 inline-block underline underline-offset-4 hover:text-white" href={`mailto:${businessDetails.supportEmail}`}>{businessDetails.supportEmail}</a></div><PaymentMethods/></div><div className="shell border-t border-white/15 py-5 text-xs text-zinc-400">{t.footer.copyright}</div></footer>; }
function FooterGroup({ title, links, locale }: { title: string; links: [string, string][]; locale: Locale }) { return <div><h2 className="text-sm font-bold">{title}</h2><ul className="mt-4 grid gap-3">{links.map(([label, href]) => <li key={href}><Link className="inline-flex items-center gap-1 text-sm text-zinc-300 hover:text-[var(--lime)]" href={`/${locale}${href}`}>{label}<ArrowUpRight size={13}/></Link></li>)}</ul></div>; }
