"use server";

import { revalidatePath } from "next/cache";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { getDatabase } from "@/db/client";
import { banners, contentArticles, mediaAssets } from "@/db/schema";
import { writeAuditLog } from "@/lib/admin/audit";
import { requirePermission } from "@/lib/admin/auth";

export type ContentState = { success: boolean; message: string };
export const initialContentState: ContentState = { success: false, message: "" };
const slug = z.string().trim().min(2).max(260).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Slug 仅支持小写英文、数字和连字符。");
const articleSchema = z.object({ id: z.string().uuid().optional(), type: z.enum(["news", "blog"]), title: z.string().trim().min(2).max(255), slug, excerpt: z.string().trim().max(1000).optional(), body: z.string().trim().max(30000).optional(), status: z.enum(["draft", "scheduled", "published", "offline"]), seoTitle: z.string().trim().max(255).optional(), seoDescription: z.string().trim().max(320).optional(), seoKeywords: z.string().trim().max(1000).optional() });
const bannerSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(160), placement: z.string().trim().min(2).max(80), imageUrl: z.string().url("请填写有效图片 URL。"), mobileImageUrl: z.union([z.literal(""), z.string().url("移动端图片 URL 不正确。")]), targetUrl: z.union([z.literal(""), z.string().url("跳转 URL 不正确。")]), sortOrder: z.coerce.number().int().min(0).max(100000), isActive: z.enum(["true", "false"]) });
const mediaSchema = z.object({ url: z.string().url("请填写有效媒体 URL。"), altText: z.string().trim().max(255).optional(), mimeType: z.string().trim().max(128).optional() });
async function done(actorId: string, action: string, type: string, id: string | undefined, result: "success" | "failure", path: string) { await writeAuditLog({ actorId, action, resourceType: type, resourceId: id, result }); revalidatePath(path); }

export async function saveArticleAction(_state: ContentState, formData: FormData): Promise<ContentState> { const actor = await requirePermission("customers.update"); const parsed = articleSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { success: false, message: parsed.error.issues[0]?.message ?? "内容不完整。" }; const v = parsed.data; const path = `/admin/${v.type}`; try { let id = v.id; const values = { type: v.type, title: v.title, slug: v.slug, excerpt: v.excerpt || null, body: v.body || null, status: v.status, seoTitle: v.seoTitle || null, seoDescription: v.seoDescription || null, seoKeywords: v.seoKeywords || null, publishedAt: v.status === "published" ? new Date() : null, updatedAt: new Date() }; if (id) await getDatabase().update(contentArticles).set(values).where(eq(contentArticles.id, id)); else { const [created] = await getDatabase().insert(contentArticles).values({ ...values, createdBy: actor.id }).returning({ id: contentArticles.id }); id = created?.id; } await done(actor.id, `content.article.${v.id ? "update" : "create"}`, "content_article", id, "success", path); return { success: true, message: v.id ? "内容已保存。" : "内容已创建。" }; } catch (error) { console.error("保存内容失败", error); await done(actor.id, "content.article.save", "content_article", undefined, "failure", path); return { success: false, message: "保存失败，请确认同类型的 Slug 未重复。" }; } }
export async function saveBannerAction(_state: ContentState, formData: FormData): Promise<ContentState> { const actor = await requirePermission("customers.update"); const parsed = bannerSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { success: false, message: parsed.error.issues[0]?.message ?? "Banner 信息不完整。" }; const v = parsed.data; try { let id = v.id; const values = { name: v.name, placement: v.placement, imageUrl: v.imageUrl, mobileImageUrl: v.mobileImageUrl || null, targetUrl: v.targetUrl || null, sortOrder: v.sortOrder, isActive: v.isActive === "true", updatedAt: new Date() }; if (id) await getDatabase().update(banners).set(values).where(eq(banners.id, id)); else { const [created] = await getDatabase().insert(banners).values(values).returning({ id: banners.id }); id = created?.id; } await done(actor.id, `content.banner.${v.id ? "update" : "create"}`, "banner", id, "success", "/admin/banners"); return { success: true, message: v.id ? "Banner 已保存。" : "Banner 已创建。" }; } catch (error) { console.error("保存 Banner 失败", error); return { success: false, message: "Banner 保存失败。" }; } }
export async function registerMediaAction(_state: ContentState, formData: FormData): Promise<ContentState> { const actor = await requirePermission("customers.update"); const parsed = mediaSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { success: false, message: parsed.error.issues[0]?.message ?? "媒体地址不正确。" }; const v = parsed.data; try { await getDatabase().insert(mediaAssets).values({ provider: "external", objectKey: v.url, url: v.url, altText: v.altText || null, mimeType: v.mimeType || null, createdBy: actor.id }); await done(actor.id, "content.media.register", "media_asset", undefined, "success", "/admin/media"); return { success: true, message: "媒体资源已登记。" }; } catch (error) { console.error("登记媒体失败", error); return { success: false, message: "登记失败，媒体地址可能已存在。" }; } }
