import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { getDatabase } from "@/db/client";
import { customerLoyaltyLedgers, customers, orders } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";

export default async function CustomerDetailPage({ params }: { params: Promise<{ customerId: string }> }) { await requirePermission("customers.read"); const { customerId } = await params; const db = getDatabase(); const [customer] = await db.select().from(customers).where(eq(customers.id, customerId)).limit(1); if (!customer) notFound(); const [customerOrders, loyalty] = await Promise.all([db.select().from(orders).where(eq(orders.customerId, customer.id)).orderBy(desc(orders.createdAt)), db.select().from(customerLoyaltyLedgers).where(eq(customerLoyaltyLedgers.customerId, customer.id)).orderBy(desc(customerLoyaltyLedgers.createdAt))]); const total = customerOrders.reduce((sum, order) => sum + Number(order.totalAmount), 0); return <div className="mx-auto max-w-5xl px-5 py-7 sm:px-8 lg:px-10"><Link href="/admin/customers" className="text-sm font-bold text-[#477b38]">← 返回客户列表</Link><div className="mt-5 border-b border-black/10 pb-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#538a42]">客户档案</p><h1 className="mt-2 font-serif text-4xl font-bold">{[customer.firstName, customer.lastName].filter(Boolean).join(" ") || "未命名客户"}</h1><p className="mt-2 text-sm text-black/55">{customer.email ?? "—"} · {customer.phone ?? "—"}</p></div><div className="mt-6 grid gap-5 md:grid-cols-3"><Card label="订单数" value={`${customerOrders.length} 笔`}/><Card label="累计订单金额" value={`USD ${total.toFixed(2)}`}/><Card label="营销订阅" value={customer.acceptsMarketing ? "已订阅" : "未订阅"}/></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="font-serif text-2xl font-bold">订单历史</h2>{customerOrders.length ? <div className="mt-4 grid gap-3">{customerOrders.map((order) => <Link key={order.id} href={`/admin/orders/${order.id}`} className="rounded-xl border border-black/8 p-4 hover:border-[#548544]"><p className="font-mono text-sm font-bold">{order.orderNumber}</p><p className="mt-1 text-sm text-black/55">{order.status} · {order.currency} {order.totalAmount}</p></Link>)}</div> : <p className="mt-4 text-sm text-black/55">暂无订单。</p>}</section><section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="font-serif text-2xl font-bold">客户资料</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-black/50">来源</dt><dd className="mt-1 font-semibold">{customer.source ?? "—"}</dd></div><div><dt className="text-black/50">备注</dt><dd className="mt-1 whitespace-pre-wrap">{customer.notes ?? "—"}</dd></div><div><dt className="text-black/50">积分 / 余额流水</dt><dd className="mt-1 font-semibold">{loyalty.length} 条</dd></div></dl></section></div></div>; }
function Card({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-black/10 bg-white p-5"><p className="text-sm text-black/55">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p></article>; }
