"use client";
import Image from "next/image";
import Link from "next/link";
import { ChevronDown, ShieldCheck, Truck, Undo2 } from "lucide-react";
import { useState } from "react";
import type { Product } from "@/types/product";
import { localize, type Locale } from "@/lib/i18n";
import { messages } from "@/messages";
import { Price } from "@/components/commerce/price";
import { AddToCart } from "./add-to-cart";
import { ProductCard } from "./product-card";
import { products } from "@/data/fixtures/products";

export function ProductDetail({ product, locale }: { product: Product; locale: Locale }) { const [sku, setSku] = useState(product.colors[0]); const t = messages[locale]; return <>
  <section className="shell grid gap-8 py-8 lg:grid-cols-[1.2fr_.8fr] lg:py-14"><div className="grid gap-4"><div className="overflow-hidden rounded-3xl bg-[#eeefeb]"><Image src={sku.images[0]} alt={`${localize(product.name, locale)} in ${localize(sku.name, locale)}`} width={1400} height={1200} priority className="aspect-square w-full object-cover" sizes="(max-width: 1024px) 100vw, 60vw"/></div>{sku.video && <div className="grid aspect-video place-items-center rounded-2xl bg-[var(--dark)] text-white">Demo video slot</div>}</div>
    <div className="lg:sticky lg:top-24 lg:self-start"><p className="eyebrow">{product.demo ? t.common.demo : "Now available"}</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em] md:text-5xl">{localize(product.name, locale)}</h1><p className="mt-4 text-lg leading-7 text-[var(--muted)]">{localize(product.tagline, locale)}</p><div className="mt-6">{product.demo ? <Price usd={product.usdPrice} locale={locale}/> : <div><div className="flex items-baseline gap-3"><span className="text-lg font-bold text-[var(--muted)] line-through">USD {product.compareAtUsdPrice?.toFixed(2).replace(/\\.00$/, "")}</span><span className="text-3xl font-black tracking-tight">USD {product.usdPrice.toFixed(2).replace(/\\.00$/, "")}</span></div><p className="mt-2 text-sm text-[var(--muted)]">Launch price. Original price USD {product.compareAtUsdPrice?.toFixed(2).replace(/\\.00$/, "")}.</p></div>}</div><fieldset className="mt-7"><legend className="font-bold">{t.common.chooseColor}</legend><div className="mt-3 flex flex-wrap gap-2">{product.colors.map((color) => <button key={color.id} onClick={() => setSku(color)} className={`flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-bold ${color.id === sku.id ? "border-[var(--ink)] bg-[var(--surface)]" : "border-[var(--line)]"}`}><span className="h-4 w-4 rounded-full border border-black/10" style={{ background: color.hex }}/>{localize(color.name, locale)}</button>)}</div></fieldset><div className="mt-7">{product.demo ? <AddToCart product={product} skuId={sku.id} locale={locale}/> : <Link className="button-primary w-full" href={`/${locale}/support/contact?product=${product.slug}`}>Request order / Contact sales</Link>}</div><div className="mt-6 grid gap-3 border-t border-[var(--line)] pt-6 text-sm"><Notice icon={<Truck size={18}/>} title={t.product.dispatch}/><Notice icon={<Undo2 size={18}/>} title="30-day returns. Terms and return shipping conditions apply."/><Notice icon={<ShieldCheck size={18}/>} title="6-month limited warranty. Draft policy details apply."/><p className="text-[var(--muted)]">{t.product.tax}</p></div></div></section>
  <section className="shell grid gap-12 py-12 lg:grid-cols-[.9fr_1.1fr]"><div><h2 className="text-3xl font-black tracking-[-.05em]">Built around the moments you keep.</h2><p className="mt-4 leading-7 text-[var(--muted)]">{localize(product.description, locale)}</p>{product.translationNote && <InfoBlock title={t.product.translation} text={localize(product.translationNote, locale)}/>} {product.prescriptionNote && <InfoBlock title={t.product.prescription} text={localize(product.prescriptionNote, locale)} link={{ label: t.product.lensLink, href: `/${locale}/lens-guide` }}/>}</div><div className="grid gap-3">{product.camera && <InfoBlock title={t.product.camera} text={`Photo: ${product.camera.photo}. Video: ${product.camera.video}. Storage: ${product.camera.storage}. Battery: ${product.camera.battery}.`}/>}<Disclosure title={t.product.specs}><div className="grid gap-4 sm:grid-cols-2">{product.specifications.map((spec) => <div key={spec.label.en} className="rounded-xl bg-[var(--surface)] p-4"><p className="text-xs font-bold uppercase tracking-wide text-[var(--muted)]">{localize(spec.label, locale)}</p><p className="mt-2 font-bold">{localize(spec.value, locale)}</p></div>)}</div></Disclosure><Disclosure title={t.product.box}><ul className="grid gap-2 text-[var(--muted)]">{product.inTheBox.map((item) => <li key={item.en}>• {localize(item, locale)}</li>)}</ul></Disclosure><Disclosure title={t.product.compatibility}><p className="leading-7 text-[var(--muted)]">{localize(product.compatibility, locale)}</p></Disclosure><Disclosure title={t.product.faq}>{product.faq.length ? product.faq.map((faq) => <div className="mb-5" key={faq.question.en}><p className="font-bold">{localize(faq.question, locale)}</p><p className="mt-2 leading-6 text-[var(--muted)]">{localize(faq.answer, locale)}</p></div>) : <p className="text-[var(--muted)]">Demo FAQ content will be updated with confirmed product documentation.</p>}</Disclosure></div></section>
  <section className="shell border-t border-[var(--line)] py-12"><h2 className="text-3xl font-black tracking-[-.05em]">{t.product.related}</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{products.filter((candidate) => !candidate.demo && candidate.id !== product.id).slice(0, 3).map((candidate) => <ProductCard product={candidate} locale={locale} key={candidate.id}/>)}</div></section>
  </>; }
function Notice({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex gap-3"><span className="mt-0.5 text-[var(--muted)]">{icon}</span><p>{title}</p></div>; }
function InfoBlock({ title, text, link }: { title: string; text: string; link?: { label: string; href: string } }) { return <div className="mt-7 rounded-2xl bg-[#eaf0d9] p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 leading-7 text-[var(--muted)]">{text}</p>{link && <Link className="mt-4 inline-block font-bold underline underline-offset-4" href={link.href}>{link.label}</Link>}</div>; }
function Disclosure({ title, children }: { title: string; children: React.ReactNode }) { const [open, setOpen] = useState(false); return <div className="border-b border-[var(--line)]"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between py-5 text-start font-black" aria-expanded={open}>{title}<ChevronDown className={open ? "rotate-180" : ""}/></button>{open && <div className="pb-5">{children}</div>}</div>; }
