"use client";
import Image from "next/image";
import Link from "next/link";
import { ChevronDown, FileText } from "lucide-react";
import { useState } from "react";
import type { Product } from "@/types/product";
import { localize, type Locale } from "@/lib/i18n";
import { ProductCard } from "./product-card";
import { products } from "@/data/fixtures/products";

export function ProductDetail({ product, locale }: { product: Product; locale: Locale }) {
  const [sku, setSku] = useState(product.colors[0]);
  return <>
    <section className="shell grid gap-8 py-8 lg:grid-cols-[1.2fr_.8fr] lg:py-14"><div className="grid gap-4"><div className="overflow-hidden rounded-3xl bg-[#eeefeb]"><Image src={sku.images[0]} alt={`${localize(product.name, locale)} in ${localize(sku.name, locale)}`} width={1400} height={1200} priority className="aspect-square w-full object-cover" sizes="(max-width: 1024px) 100vw, 60vw"/></div></div>
      <div className="lg:sticky lg:top-24 lg:self-start"><p className="eyebrow">Product catalogue</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em] md:text-5xl">{localize(product.name, locale)}</h1><p className="mt-4 text-lg leading-7 text-[var(--muted)]">{localize(product.tagline, locale)}</p><p className="mt-6 rounded-2xl bg-[#eaf0d9] p-5 text-sm leading-6">Pricing, minimum order quantities, delivery and regional availability are provided on request.</p><fieldset className="mt-7"><legend className="font-bold">Product image</legend><div className="mt-3 flex flex-wrap gap-2">{product.colors.map((color) => <button key={color.id} onClick={() => setSku(color)} className={`flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-bold ${color.id === sku.id ? "border-[var(--ink)] bg-[var(--surface)]" : "border-[var(--line)]"}`}><span className="h-4 w-4 rounded-full border border-black/10" style={{ background: color.hex }}/>{localize(color.name, locale)}</button>)}</div></fieldset><Link className="button-primary mt-7 w-full" href={`/${locale}/support/contact?model=${encodeURIComponent(localize(product.name, locale))}`}><FileText size={18}/>Request product details</Link><p className="mt-4 text-xs leading-5 text-[var(--muted)]">This catalogue does not accept online orders or payments.</p></div></section>
    <section className="shell grid gap-12 py-12 lg:grid-cols-[.9fr_1.1fr]"><div><h2 className="text-3xl font-black tracking-[-.05em]">Model overview</h2><p className="mt-4 leading-7 text-[var(--muted)]">{localize(product.description, locale)}</p></div><div className="grid gap-3"><Disclosure title="Specifications"><div className="grid gap-4 sm:grid-cols-2">{product.specifications.map((spec) => <div key={spec.label.en} className="rounded-xl bg-[var(--surface)] p-4"><p className="text-xs font-bold uppercase tracking-wide text-[var(--muted)]">{localize(spec.label, locale)}</p><p className="mt-2 font-bold">{localize(spec.value, locale)}</p></div>)}</div></Disclosure><Disclosure title="In the box"><ul className="grid gap-2 text-[var(--muted)]">{product.inTheBox.map((item) => <li key={item.en}>• {localize(item, locale)}</li>)}</ul></Disclosure><Disclosure title="Compatibility"><p className="leading-7 text-[var(--muted)]">{localize(product.compatibility, locale)}</p></Disclosure><Disclosure title="Product FAQ">{product.faq.map((faq) => <div className="mb-5" key={faq.question.en}><p className="font-bold">{localize(faq.question, locale)}</p><p className="mt-2 leading-6 text-[var(--muted)]">{localize(faq.answer, locale)}</p></div>)}</Disclosure></div></section>
    <section className="shell border-t border-[var(--line)] py-12"><h2 className="text-3xl font-black tracking-[-.05em]">Related products</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{products.filter((candidate) => candidate.id !== product.id).slice(0, 3).map((candidate) => <ProductCard product={candidate} locale={locale} key={candidate.id}/>)}</div></section>
  </>;
}
function Disclosure({ title, children }: { title: string; children: React.ReactNode }) { const [open, setOpen] = useState(false); return <div className="border-b border-[var(--line)]"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between py-5 text-start font-black" aria-expanded={open}>{title}<ChevronDown className={open ? "rotate-180" : ""}/></button>{open && <div className="pb-5">{children}</div>}</div>; }
