import { desc, eq } from "drizzle-orm";
import { ArticleForm } from "@/components/admin/content-forms";
import { getDatabase } from "@/db/client";
import { contentArticles } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";
export default async function NewsPage() { await requirePermission("customers.read"); const rows = await getDatabase().select().from(contentArticles).where(eq(contentArticles.type, "news")).orderBy(desc(contentArticles.updatedAt)); return <main className="mx-auto max-w-[1560px] px-5 py-7 sm:px-8 lg:px-10"><Header title="新闻管理" description="创建新闻草稿、安排发布、下线与管理 SEO。"/><section className="mt-6 grid gap-6 xl:grid-cols-[390px_minmax(0,1fr)]"><aside><h2 className="mb-3 font-serif text-2xl font-bold">新建新闻</h2><ArticleForm type="news"/></aside><List type="news" rows={rows}/></section></main>; }
function Header({ title, description }: { title: string; description: string }) { return <header className="border-b border-black/10 pb-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#538a42]">客户与内容</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-[-.04em]">{title}</h1><p className="mt-2 text-sm text-black/55">{description}</p></header>; }
function List({ type, rows }: { type: "news" | "blog"; rows: Awaited<ReturnType<typeof getRows>> }) { return <div className="grid gap-4">{rows.length ? rows.map((row) => <details key={row.id} className="rounded-2xl border border-black/10 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5"><div><p className="font-bold">{row.title}</p><p className="mt-1 font-mono text-xs text-black/45">/{row.slug}</p></div><span className="rounded-full bg-[#edf4e9] px-2.5 py-1 text-xs font-bold text-[#3e752e]">{row.status}</span></summary><div className="border-t border-black/8 p-5"><ArticleForm type={type} record={row}/></div></details>) : <div className="rounded-2xl border border-dashed border-black/15 bg-white p-12 text-center text-sm text-black/55">暂无新闻内容。</div>}</div>; }
async function getRows() { return getDatabase().select().from(contentArticles).where(eq(contentArticles.type, "news")); }
