import type { Locale } from "@/lib/i18n";

const en = {
  checkout: "Order checkout",
  title: "Confirm your order.",
  intro:
    "Select your destination to see an estimated international shipping charge in USD before secure payment.",
  contact: "Contact",
  email: "Email address",
  firstName: "First name",
  lastName: "Last name",
  phone: "Phone / WhatsApp",
  marketing: "Receive product updates and order follow-up.",
  account: "Member account",
  accountCopy:
    "Your order automatically becomes part of a member account. Set a password to view orders from any browser. If this email already has an account, enter its password.",
  password: "Account password (10+ characters)",
  confirmPassword: "Confirm account password",
  passwordMismatch: "The account passwords do not match.",
  delivery: "Delivery",
  address: "Address",
  city: "City",
  province: "State / province",
  postal: "ZIP / postal code",
  country: "Country / region",
  chooseCountry: "Choose destination country / region",
  shippingMethod: "Shipping method",
  shippingMethodTitle: "International delivery — destination estimate",
  shippingMethodCopy:
    "The shown shipping charge is automatically matched to your selected destination.",
  chooseDestination: "Select a destination",
  chooseDestinationCopy:
    "Choose a destination to calculate shipping. Every pair is estimated at 0.5 kg.",
  estimatedShipping: "Estimated shipping",
  flatRate: "Flat delivery charge for this destination.",
  basedOn: "Based on",
  pair: "pair",
  pairs: "pairs",
  actualWeight: "actual weight",
  billedWeight: "billed weight",
  includes: "Includes",
  handling: "handling adjustment",
  carrier: "carrier fee",
  converted: "Converted from",
  dimension: "Dimensional weight may change the final charge.",
  coupon: "Coupon",
  couponCopy:
    "Enter a valid promotion code. Eligibility and discount are verified securely when the order is created.",
  couponCode: "Coupon code",
  payment: "Payment preference",
  paymentCopy:
    "For card payments, Oceanpayment's secure component appears after your order is created.",
  card: "Credit card",
  cardCopy: "Pay securely using the embedded Oceanpayment card component.",
  secure: "Secure checkout",
  transfer: "Bank transfer / T/T",
  transferCopy:
    "Request a proforma invoice and verified bank details from sales.",
  invoice: "Invoice",
  notes: "Order notes",
  notesPlaceholder: "Color, delivery plan or other order details.",
  policies: "Terms and policies",
  policyConsent:
    "I have reviewed and agree to the Terms of Service, Privacy Policy, Shipping & Delivery and Returns & Refunds.",
  openNotice: "Open checkout terms notice",
  summary: "Order summary",
  unit: "unit",
  units: "units",
  shipping: "Shipping",
  estimatedTotal: "Estimated total",
  creating: "Creating order…",
  ready: "Secure payment ready",
  continuePayment: "Continue to secure payment",
  submit: "Submit order request",
  estimateNote:
    "The shipping quote is an estimate. Card information is handled by Oceanpayment's secure component.",
  matched: "Shipping is matched to your selected destination.",
  provider:
    "Card transactions are confirmed only after a verified provider notification.",
  volume: "Sales verifies volumetric weight before fulfillment.",
  empty: "Your checkout is empty.",
  emptyCopy: "Choose a product before submitting an order request.",
  browse: "Browse products",
  returnReceived: "Payment return received",
  confirming: "We're confirming your payment.",
  returnCopy:
    "Your card response has returned safely. Order status changes only after Oceanpayment's verified server notification.",
  orderReceived: "Order request received",
  thankYou: "Thank you.",
  orderCopy:
    "Your request has been created. You are now signed in to your member account. Sales will reconfirm stock, dimensional weight and secure payment instructions before any charge.",
  continueShopping: "Continue shopping",
  orderError: "Unable to create your order. Check the form and try again.",
  accountInvalid: "The password for this member email is incorrect.",
  accountLocked:
    "This member account is temporarily locked. Try again later or contact support.",
  shippingUnavailable: "Delivery is unavailable for this destination.",
  paymentUnavailable:
    "Card payment is temporarily unavailable. Choose bank transfer or try again later.",
};
type CheckoutCopy = typeof en;

export const checkoutCopy: Record<Locale, CheckoutCopy> = {
  en,
  ar: {
    checkout: "إتمام الطلب",
    title: "أكد طلبك.",
    intro:
      "اختر وجهتك لعرض تكلفة الشحن الدولي التقديرية بالدولار قبل الدفع الآمن.",
    contact: "بيانات الاتصال",
    email: "البريد الإلكتروني",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    phone: "الهاتف / واتساب",
    marketing: "تلقي تحديثات المنتجات ومتابعة الطلب.",
    account: "حساب العضو",
    accountCopy:
      "يُضاف طلبك تلقائياً إلى حساب عضو. أنشئ كلمة مرور لعرض الطلبات من أي متصفح. إذا كان البريد مسجلاً، أدخل كلمة المرور الحالية.",
    password: "كلمة مرور الحساب (10 أحرف على الأقل)",
    confirmPassword: "تأكيد كلمة المرور",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    delivery: "التوصيل",
    address: "العنوان",
    city: "المدينة",
    province: "الولاية / المنطقة",
    postal: "الرمز البريدي",
    country: "الدولة / المنطقة",
    chooseCountry: "اختر دولة / منطقة التوصيل",
    shippingMethod: "طريقة الشحن",
    shippingMethodTitle: "توصيل دولي — تقدير حسب الوجهة",
    shippingMethodCopy: "تتم مطابقة رسوم الشحن تلقائياً مع الوجهة المحددة.",
    chooseDestination: "اختر وجهة",
    chooseDestinationCopy:
      "اختر وجهة لحساب الشحن. الوزن التقديري لكل نظارة 0.5 كجم.",
    estimatedShipping: "الشحن التقديري",
    flatRate: "رسوم توصيل ثابتة لهذه الوجهة.",
    basedOn: "بناءً على",
    pair: "نظارة",
    pairs: "نظارات",
    actualWeight: "الوزن الفعلي",
    billedWeight: "الوزن المحتسب",
    includes: "يشمل",
    handling: "تعديل المناولة",
    carrier: "رسوم الناقل",
    converted: "محول من",
    dimension: "قد يغيّر الوزن الحجمي الرسوم النهائية.",
    coupon: "قسيمة",
    couponCopy: "أدخل رمزاً صالحاً وسيتم التحقق منه بأمان عند إنشاء الطلب.",
    couponCode: "رمز القسيمة",
    payment: "طريقة الدفع",
    paymentCopy:
      "عند الدفع بالبطاقة يظهر مكون Oceanpayment الآمن بعد إنشاء الطلب.",
    card: "بطاقة ائتمان",
    cardCopy: "ادفع بأمان عبر مكون Oceanpayment المدمج.",
    secure: "دفع آمن",
    transfer: "تحويل بنكي / T/T",
    transferCopy: "اطلب فاتورة أولية وبيانات بنكية موثقة من المبيعات.",
    invoice: "فاتورة",
    notes: "ملاحظات الطلب",
    notesPlaceholder: "اللون أو خطة التوصيل أو تفاصيل أخرى.",
    policies: "الشروط والسياسات",
    policyConsent:
      "راجعت وأوافق على شروط الخدمة وسياسة الخصوصية والشحن والتسليم والإرجاع والاسترداد.",
    openNotice: "فتح إشعار شروط الدفع",
    summary: "ملخص الطلب",
    unit: "قطعة",
    units: "قطع",
    shipping: "الشحن",
    estimatedTotal: "الإجمالي التقديري",
    creating: "جارٍ إنشاء الطلب…",
    ready: "الدفع الآمن جاهز",
    continuePayment: "المتابعة إلى الدفع الآمن",
    submit: "إرسال طلب الشراء",
    estimateNote:
      "سعر الشحن تقديري. تتولى Oceanpayment معالجة بيانات البطاقة بأمان.",
    matched: "تمت مطابقة الشحن مع وجهتك.",
    provider: "لا يتم تأكيد البطاقة إلا بعد إشعار موثق من مزود الدفع.",
    volume: "يتحقق فريق المبيعات من الوزن الحجمي قبل التنفيذ.",
    empty: "صفحة الدفع فارغة.",
    emptyCopy: "اختر منتجاً قبل إرسال الطلب.",
    browse: "تصفح المنتجات",
    returnReceived: "تم استلام عودة الدفع",
    confirming: "جارٍ تأكيد دفعتك.",
    returnCopy:
      "عادت استجابة البطاقة بأمان، ولا تتغير حالة الطلب إلا بعد إشعار الخادم الموثق.",
    orderReceived: "تم استلام الطلب",
    thankYou: "شكراً لك.",
    orderCopy:
      "تم إنشاء طلبك وتسجيل دخولك إلى حساب العضو. سيؤكد فريق المبيعات المخزون والوزن وتعليمات الدفع قبل أي خصم.",
    continueShopping: "متابعة التسوق",
    orderError: "تعذر إنشاء الطلب. تحقق من البيانات وحاول مجدداً.",
    accountInvalid: "كلمة المرور لهذا البريد غير صحيحة.",
    accountLocked: "حساب العضو مقفل مؤقتاً. حاول لاحقاً أو تواصل مع الدعم.",
    shippingUnavailable: "التوصيل غير متاح لهذه الوجهة.",
    paymentUnavailable:
      "الدفع بالبطاقة غير متاح مؤقتاً. اختر التحويل البنكي أو حاول لاحقاً.",
  },
  es: {
    checkout: "Finalizar pedido",
    title: "Confirma tu pedido.",
    intro:
      "Elige tu destino para ver el envío internacional estimado en USD antes del pago seguro.",
    contact: "Contacto",
    email: "Correo electrónico",
    firstName: "Nombre",
    lastName: "Apellidos",
    phone: "Teléfono / WhatsApp",
    marketing: "Recibir novedades y seguimiento del pedido.",
    account: "Cuenta de miembro",
    accountCopy:
      "Tu pedido se añade automáticamente a una cuenta. Crea una contraseña para verlo desde cualquier navegador. Si el correo ya tiene cuenta, introduce su contraseña.",
    password: "Contraseña (10+ caracteres)",
    confirmPassword: "Confirmar contraseña",
    passwordMismatch: "Las contraseñas no coinciden.",
    delivery: "Entrega",
    address: "Dirección",
    city: "Ciudad",
    province: "Estado / provincia",
    postal: "Código postal",
    country: "País / región",
    chooseCountry: "Elige país / región de destino",
    shippingMethod: "Método de envío",
    shippingMethodTitle: "Entrega internacional — estimación por destino",
    shippingMethodCopy:
      "El cargo se asigna automáticamente al destino seleccionado.",
    chooseDestination: "Elige un destino",
    chooseDestinationCopy:
      "Elige un destino para calcular el envío. Cada par se estima en 0,5 kg.",
    estimatedShipping: "Envío estimado",
    flatRate: "Tarifa fija para este destino.",
    basedOn: "Calculado para",
    pair: "par",
    pairs: "pares",
    actualWeight: "peso real",
    billedWeight: "peso facturable",
    includes: "Incluye",
    handling: "ajuste de gestión",
    carrier: "tarifa del transportista",
    converted: "Convertido desde",
    dimension: "El peso volumétrico puede cambiar el cargo final.",
    coupon: "Cupón",
    couponCopy:
      "Introduce un código válido. Se verificará de forma segura al crear el pedido.",
    couponCode: "Código de cupón",
    payment: "Preferencia de pago",
    paymentCopy:
      "Para tarjeta, el componente seguro de Oceanpayment aparece después de crear el pedido.",
    card: "Tarjeta de crédito",
    cardCopy:
      "Paga de forma segura con el componente integrado de Oceanpayment.",
    secure: "Pago seguro",
    transfer: "Transferencia bancaria / T/T",
    transferCopy:
      "Solicita una factura proforma y datos bancarios verificados.",
    invoice: "Factura",
    notes: "Notas del pedido",
    notesPlaceholder: "Color, plan de entrega u otros detalles.",
    policies: "Términos y políticas",
    policyConsent:
      "He revisado y acepto los Términos, Privacidad, Envío y Devoluciones.",
    openNotice: "Abrir aviso del checkout",
    summary: "Resumen del pedido",
    unit: "unidad",
    units: "unidades",
    shipping: "Envío",
    estimatedTotal: "Total estimado",
    creating: "Creando pedido…",
    ready: "Pago seguro listo",
    continuePayment: "Continuar al pago seguro",
    submit: "Enviar solicitud",
    estimateNote:
      "El envío es estimado. Oceanpayment gestiona de forma segura los datos de tarjeta.",
    matched: "El envío coincide con el destino elegido.",
    provider:
      "La tarjeta solo se confirma tras una notificación verificada del proveedor.",
    volume: "Ventas verifica el peso volumétrico antes de preparar el pedido.",
    empty: "Tu checkout está vacío.",
    emptyCopy: "Elige un producto antes de enviar el pedido.",
    browse: "Ver productos",
    returnReceived: "Respuesta de pago recibida",
    confirming: "Estamos confirmando tu pago.",
    returnCopy:
      "La respuesta de la tarjeta volvió de forma segura. El estado solo cambia tras la notificación verificada.",
    orderReceived: "Solicitud recibida",
    thankYou: "Gracias.",
    orderCopy:
      "Tu solicitud se creó y has iniciado sesión en tu cuenta. Ventas confirmará stock, peso e instrucciones antes de cualquier cargo.",
    continueShopping: "Seguir comprando",
    orderError:
      "No se pudo crear el pedido. Revisa el formulario e inténtalo de nuevo.",
    accountInvalid: "La contraseña de esta cuenta no es correcta.",
    accountLocked:
      "La cuenta está bloqueada temporalmente. Inténtalo más tarde o contacta con soporte.",
    shippingUnavailable: "La entrega no está disponible para este destino.",
    paymentUnavailable:
      "El pago con tarjeta no está disponible temporalmente. Elige transferencia o inténtalo más tarde.",
  },
  pt: {
    checkout: "Finalizar pedido",
    title: "Confirme seu pedido.",
    intro:
      "Escolha o destino para ver o frete internacional estimado em USD antes do pagamento seguro.",
    contact: "Contato",
    email: "E-mail",
    firstName: "Nome",
    lastName: "Sobrenome",
    phone: "Telefone / WhatsApp",
    marketing: "Receber novidades e acompanhamento do pedido.",
    account: "Conta de membro",
    accountCopy:
      "Seu pedido é adicionado automaticamente a uma conta. Crie uma senha para acessá-lo em qualquer navegador. Se o e-mail já tiver conta, informe a senha.",
    password: "Senha (10+ caracteres)",
    confirmPassword: "Confirmar senha",
    passwordMismatch: "As senhas não coincidem.",
    delivery: "Entrega",
    address: "Endereço",
    city: "Cidade",
    province: "Estado / província",
    postal: "CEP / código postal",
    country: "País / região",
    chooseCountry: "Escolha o país / região",
    shippingMethod: "Método de envio",
    shippingMethodTitle: "Entrega internacional — estimativa por destino",
    shippingMethodCopy:
      "O frete é associado automaticamente ao destino escolhido.",
    chooseDestination: "Escolha um destino",
    chooseDestinationCopy:
      "Escolha um destino para calcular o frete. Cada óculos é estimado em 0,5 kg.",
    estimatedShipping: "Frete estimado",
    flatRate: "Tarifa fixa para este destino.",
    basedOn: "Calculado para",
    pair: "óculos",
    pairs: "óculos",
    actualWeight: "peso real",
    billedWeight: "peso cobrado",
    includes: "Inclui",
    handling: "ajuste de manuseio",
    carrier: "taxa da transportadora",
    converted: "Convertido de",
    dimension: "O peso cúbico pode alterar a cobrança final.",
    coupon: "Cupom",
    couponCopy:
      "Informe um código válido. A elegibilidade será verificada com segurança.",
    couponCode: "Código do cupom",
    payment: "Forma de pagamento",
    paymentCopy:
      "No cartão, o componente seguro da Oceanpayment aparece após criar o pedido.",
    card: "Cartão de crédito",
    cardCopy: "Pague com segurança no componente integrado da Oceanpayment.",
    secure: "Checkout seguro",
    transfer: "Transferência bancária / T/T",
    transferCopy: "Solicite fatura proforma e dados bancários verificados.",
    invoice: "Fatura",
    notes: "Observações",
    notesPlaceholder: "Cor, plano de entrega ou outros detalhes.",
    policies: "Termos e políticas",
    policyConsent: "Li e aceito os Termos, Privacidade, Entrega e Devoluções.",
    openNotice: "Abrir aviso do checkout",
    summary: "Resumo do pedido",
    unit: "unidade",
    units: "unidades",
    shipping: "Frete",
    estimatedTotal: "Total estimado",
    creating: "Criando pedido…",
    ready: "Pagamento seguro pronto",
    continuePayment: "Continuar para pagamento",
    submit: "Enviar pedido",
    estimateNote:
      "O frete é estimado. A Oceanpayment processa os dados do cartão com segurança.",
    matched: "O frete corresponde ao destino escolhido.",
    provider:
      "O cartão só é confirmado após notificação verificada do provedor.",
    volume: "A equipe confirma o peso cúbico antes do envio.",
    empty: "Seu checkout está vazio.",
    emptyCopy: "Escolha um produto antes de enviar o pedido.",
    browse: "Ver produtos",
    returnReceived: "Retorno do pagamento recebido",
    confirming: "Estamos confirmando seu pagamento.",
    returnCopy:
      "A resposta do cartão retornou com segurança. O status só muda após notificação verificada.",
    orderReceived: "Pedido recebido",
    thankYou: "Obrigado.",
    orderCopy:
      "Seu pedido foi criado e você entrou na conta. A equipe confirmará estoque, peso e instruções antes de qualquer cobrança.",
    continueShopping: "Continuar comprando",
    orderError:
      "Não foi possível criar o pedido. Confira os dados e tente novamente.",
    accountInvalid: "A senha desta conta está incorreta.",
    accountLocked:
      "A conta está temporariamente bloqueada. Tente mais tarde ou fale com o suporte.",
    shippingUnavailable: "A entrega não está disponível para este destino.",
    paymentUnavailable:
      "O cartão está temporariamente indisponível. Escolha transferência ou tente mais tarde.",
  },
  ja: {
    checkout: "注文手続き",
    title: "注文内容を確認。",
    intro:
      "配送先を選ぶと、安全な決済前に米ドルで国際送料の見積りを確認できます。",
    contact: "連絡先",
    email: "メールアドレス",
    firstName: "名",
    lastName: "姓",
    phone: "電話 / WhatsApp",
    marketing: "製品情報と注文フォローを受け取る。",
    account: "メンバーアカウント",
    accountCopy:
      "注文は自動的に会員アカウントへ追加されます。どのブラウザでも確認できるようパスワードを設定してください。登録済みの場合は現在のパスワードを入力します。",
    password: "パスワード（10文字以上）",
    confirmPassword: "パスワード確認",
    passwordMismatch: "パスワードが一致しません。",
    delivery: "配送",
    address: "住所",
    city: "市区町村",
    province: "都道府県 / 州",
    postal: "郵便番号",
    country: "国 / 地域",
    chooseCountry: "配送先の国 / 地域を選択",
    shippingMethod: "配送方法",
    shippingMethodTitle: "国際配送 — 配送先別見積り",
    shippingMethodCopy: "選択した配送先に送料が自動適用されます。",
    chooseDestination: "配送先を選択",
    chooseDestinationCopy:
      "配送先を選ぶと送料を計算します。1点あたり0.5kgで見積ります。",
    estimatedShipping: "送料見積り",
    flatRate: "この配送先の固定送料です。",
    basedOn: "計算条件",
    pair: "点",
    pairs: "点",
    actualWeight: "実重量",
    billedWeight: "請求重量",
    includes: "含まれるもの",
    handling: "取扱調整",
    carrier: "配送会社手数料",
    converted: "換算元",
    dimension: "容積重量により最終送料が変わる場合があります。",
    coupon: "クーポン",
    couponCopy:
      "有効なコードを入力してください。注文作成時に安全に確認します。",
    couponCode: "クーポンコード",
    payment: "支払い方法",
    paymentCopy:
      "カードの場合、注文作成後にOceanpaymentの安全な画面が表示されます。",
    card: "クレジットカード",
    cardCopy: "Oceanpaymentの埋め込み画面で安全に支払います。",
    secure: "安全な決済",
    transfer: "銀行振込 / T/T",
    transferCopy: "見積請求書と確認済み口座情報を依頼します。",
    invoice: "請求書",
    notes: "注文メモ",
    notesPlaceholder: "色、配送予定、その他の詳細。",
    policies: "規約とポリシー",
    policyConsent:
      "利用規約、プライバシー、配送、返品ポリシーを確認し同意します。",
    openNotice: "決済規約を開く",
    summary: "注文概要",
    unit: "点",
    units: "点",
    shipping: "送料",
    estimatedTotal: "見積り合計",
    creating: "注文作成中…",
    ready: "安全な決済の準備完了",
    continuePayment: "安全な決済へ進む",
    submit: "注文を送信",
    estimateNote:
      "送料は見積りです。カード情報はOceanpaymentが安全に処理します。",
    matched: "選択した配送先に送料を適用しています。",
    provider: "カード決済は確認済みの事業者通知後にのみ確定します。",
    volume: "発送前に容積重量を確認します。",
    empty: "カートに商品がありません。",
    emptyCopy: "注文前に商品を選んでください。",
    browse: "商品を見る",
    returnReceived: "決済結果を受信",
    confirming: "決済を確認しています。",
    returnCopy:
      "カード結果は安全に戻りました。確認済みのサーバー通知後に状態が更新されます。",
    orderReceived: "注文を受け付けました",
    thankYou: "ありがとうございます。",
    orderCopy:
      "注文を作成し、会員アカウントにログインしました。請求前に在庫、重量、決済案内を確認します。",
    continueShopping: "買い物を続ける",
    orderError:
      "注文を作成できませんでした。入力を確認して再試行してください。",
    accountInvalid: "この会員メールのパスワードが正しくありません。",
    accountLocked:
      "アカウントは一時的にロックされています。後で再試行するかサポートへご連絡ください。",
    shippingUnavailable: "この配送先には配送できません。",
    paymentUnavailable:
      "カード決済は一時的に利用できません。銀行振込を選ぶか後でお試しください。",
  },
  ko: {
    checkout: "주문 결제",
    title: "주문을 확인하세요.",
    intro:
      "배송 국가를 선택하면 안전한 결제 전에 USD 기준 국제 배송비를 확인할 수 있습니다.",
    contact: "연락처",
    email: "이메일",
    firstName: "이름",
    lastName: "성",
    phone: "전화 / WhatsApp",
    marketing: "제품 소식과 주문 안내 받기.",
    account: "회원 계정",
    accountCopy:
      "주문은 자동으로 회원 계정에 추가됩니다. 다른 브라우저에서도 확인할 수 있도록 비밀번호를 설정하세요. 이미 등록된 이메일이면 기존 비밀번호를 입력하세요.",
    password: "비밀번호 (10자 이상)",
    confirmPassword: "비밀번호 확인",
    passwordMismatch: "비밀번호가 일치하지 않습니다.",
    delivery: "배송",
    address: "주소",
    city: "도시",
    province: "주 / 도",
    postal: "우편번호",
    country: "국가 / 지역",
    chooseCountry: "배송 국가 / 지역 선택",
    shippingMethod: "배송 방법",
    shippingMethodTitle: "국제 배송 — 목적지별 예상",
    shippingMethodCopy: "선택한 목적지에 맞는 배송비가 자동 적용됩니다.",
    chooseDestination: "목적지 선택",
    chooseDestinationCopy:
      "목적지를 선택하면 배송비를 계산합니다. 제품 1개는 0.5kg으로 예상합니다.",
    estimatedShipping: "예상 배송비",
    flatRate: "이 목적지의 고정 배송비입니다.",
    basedOn: "계산 기준",
    pair: "개",
    pairs: "개",
    actualWeight: "실중량",
    billedWeight: "청구 중량",
    includes: "포함",
    handling: "취급 조정",
    carrier: "운송사 요금",
    converted: "환산 기준",
    dimension: "부피 중량에 따라 최종 요금이 달라질 수 있습니다.",
    coupon: "쿠폰",
    couponCopy: "유효한 코드를 입력하세요. 주문 생성 시 안전하게 확인합니다.",
    couponCode: "쿠폰 코드",
    payment: "결제 방법",
    paymentCopy:
      "카드 결제는 주문 생성 후 Oceanpayment 보안 화면이 표시됩니다.",
    card: "신용카드",
    cardCopy: "Oceanpayment 내장 화면에서 안전하게 결제합니다.",
    secure: "안전한 결제",
    transfer: "은행 송금 / T/T",
    transferCopy: "견적 송장과 확인된 계좌 정보를 요청합니다.",
    invoice: "송장",
    notes: "주문 메모",
    notesPlaceholder: "색상, 배송 계획 또는 기타 요청.",
    policies: "약관 및 정책",
    policyConsent: "이용약관, 개인정보, 배송, 반품 정책을 확인하고 동의합니다.",
    openNotice: "결제 약관 열기",
    summary: "주문 요약",
    unit: "개",
    units: "개",
    shipping: "배송비",
    estimatedTotal: "예상 합계",
    creating: "주문 생성 중…",
    ready: "안전한 결제 준비 완료",
    continuePayment: "안전한 결제로 계속",
    submit: "주문 요청 제출",
    estimateNote:
      "배송비는 예상 금액입니다. 카드 정보는 Oceanpayment가 안전하게 처리합니다.",
    matched: "선택한 목적지에 배송비가 적용됩니다.",
    provider: "카드는 확인된 결제사 알림 후에만 승인됩니다.",
    volume: "출고 전에 부피 중량을 확인합니다.",
    empty: "결제할 상품이 없습니다.",
    emptyCopy: "주문 전에 상품을 선택하세요.",
    browse: "상품 보기",
    returnReceived: "결제 결과 수신",
    confirming: "결제를 확인하고 있습니다.",
    returnCopy:
      "카드 응답이 안전하게 돌아왔습니다. 확인된 서버 알림 후 상태가 변경됩니다.",
    orderReceived: "주문 요청 접수",
    thankYou: "감사합니다.",
    orderCopy:
      "주문이 생성되고 회원 계정에 로그인되었습니다. 청구 전 재고, 중량, 결제 안내를 확인합니다.",
    continueShopping: "쇼핑 계속",
    orderError:
      "주문을 만들 수 없습니다. 입력 내용을 확인하고 다시 시도하세요.",
    accountInvalid: "이 회원 이메일의 비밀번호가 올바르지 않습니다.",
    accountLocked:
      "계정이 일시적으로 잠겼습니다. 나중에 다시 시도하거나 지원팀에 문의하세요.",
    shippingUnavailable: "이 목적지에는 배송할 수 없습니다.",
    paymentUnavailable:
      "카드 결제를 일시적으로 사용할 수 없습니다. 송금을 선택하거나 나중에 시도하세요.",
  },
};
