import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { ProductCard } from "@/components/product/product-card";
import { products } from "@/data/fixtures/products";
import type { Locale } from "@/lib/i18n";

export function HomePage({ locale }: { locale: Locale }) {
  return <>
    <section className="grid border-b border-[var(--line)] bg-[var(--paper)] lg:grid-cols-[43%_57%]"><div className="relative min-h-[55dvh] overflow-hidden bg-[#eeefeb]"><Image src="/images/products/g200-sport.webp" alt="G200 Sport Audio Glasses" fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 43vw"/></div><div className="flex flex-col justify-center px-5 py-14 md:px-10 lg:px-16"><p className="eyebrow text-[#7f9412]">CoWin Glasses</p><h1 className="mt-5 max-w-[12ch] text-5xl font-medium tracking-[-.075em] md:text-6xl lg:text-[4.45rem] lg:leading-[.92]">Smart glasses, clearly specified.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--muted)]">Explore the first published English product catalogue, built from supplied product specifications and authentic product imagery.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button-primary" href={`/${locale}/shop`}>Browse products <ArrowRight size={18}/></Link><Link className="button-secondary" href={`/${locale}/support/contact`}>Product information</Link></div><p className="mt-8 max-w-xl text-sm leading-6 text-[var(--muted)]">Pricing, availability, delivery terms and compliance requirements are confirmed per model and market.</p></div></section>
    <section className="shell py-16 md:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Published models</p><h2 className="mt-4 text-4xl font-medium tracking-[-.06em]">Start with the essentials.</h2></div><Link href={`/${locale}/shop`} className="button-secondary">View all products <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-x-5 gap-y-12 sm:grid-cols-2 xl:grid-cols-3">{products.slice(0, 3).map((product) => <ProductCard product={product} locale={locale} key={product.id}/>)}</div></section>
    <section className="border-y border-[var(--line)] bg-[#f0f3e9] py-16"><div className="shell grid gap-5 md:grid-cols-3">{[["Source-led details", "Each listed model is based on its supplied specification material."], ["No placeholder pricing", "This catalogue does not show unverified prices, stock or shipping promises."], ["Market checks first", "Verify model-specific documentation before import or distribution."]].map(([title, text]) => <div className="rounded-2xl bg-[var(--paper)] p-6" key={title}><h2 className="text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{text}</p></div>)}</div></section>
  </>;
}
