import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Headphones, Languages, Map, Video } from "lucide-react";
import { ProductCard } from "@/components/product/product-card";
import { products } from "@/data/fixtures/products";
import type { Locale } from "@/lib/i18n";
import { localize } from "@/lib/i18n";
import { messages } from "@/messages";
import { DemoForm } from "@/components/forms/demo-form";
import { Price } from "@/components/commerce/price";

export function HomePage({ locale }: { locale: Locale }) {
  const t = messages[locale]; const [flow, vision, arc] = products;
  return <>
    <section className="grid border-b border-[var(--line)] bg-[var(--paper)] lg:min-h-[calc(100dvh-120px)] lg:grid-cols-[43%_57%]">
      <div className="relative min-h-[60dvh] overflow-hidden bg-black lg:min-h-0"><Image src="/images/demo/cyclist-mountain-v2.png" alt="Demo cyclist wearing CoWin Glasses" fill priority className="object-cover object-center" sizes="(max-width: 1024px) 100vw, 43vw"/><div className="absolute inset-x-0 bottom-0 flex flex-wrap gap-x-5 gap-y-2 bg-black/45 px-5 py-4 text-xs font-semibold text-white backdrop-blur-sm"><span><i className="me-2 inline-block h-1.5 w-5 bg-[var(--lime)] align-middle"/>Open-ear audio</span><span>Hands-free control</span><span>All-day comfort</span></div></div>
      <div className="flex flex-col bg-[var(--paper)] px-5 py-10 md:px-10 lg:px-16 lg:py-12"><p className="eyebrow text-[#7f9412]">CoWin Glasses</p><h1 className="mt-5 max-w-[14ch] text-5xl font-medium tracking-[-.075em] md:text-6xl lg:text-[4.45rem] lg:leading-[.92]">Smart eyewear<br/>for every move.</h1><div className="mt-8 border-t border-[var(--line)]"><p className="pt-4 text-xs font-bold uppercase tracking-[.18em] text-[#879911]">Two ways to experience more</p><Decision product={flow} category={t.home.music} locale={locale} image="/images/demo/hero-glasses.png" number="01" detail="Open-ear audio • Bluetooth music"/><Decision product={vision} category={t.home.capture} locale={locale} image="/images/demo/hero-glasses.png" number="02" detail="Camera + translation • App connected"/></div><div className="mt-auto grid grid-cols-2 gap-y-3 border-t border-[var(--line)] pt-5 text-xs text-[var(--muted)] sm:grid-cols-4"><span>Global delivery</span><span>3 business-day dispatch</span><span>30-day returns</span><span>6-month warranty</span></div></div>
    </section>
    <section id="explore" className="grid border-b border-[var(--line)] bg-white lg:grid-cols-[1fr_1fr]"><div className="p-7 md:p-12"><p className="eyebrow">Explore by purpose</p><h2 className="mt-4 max-w-md text-4xl font-medium tracking-[-.06em]">Choose a frame for the way you move through a day.</h2><div className="mt-10 grid text-sm font-bold"><ExploreLink href={`/${locale}/collections/create`} label="Create"/><ExploreLink href={`/${locale}/collections/explore`} label="Explore"/><ExploreLink href={`/${locale}/collections/everyday`} label="Everyday"/></div></div><div className="bg-[#f0f3e9] p-7 md:p-12"><p className="eyebrow text-[#657512]">Flagship edit</p><h2 className="mt-4 text-4xl font-medium tracking-[-.06em]">{localize(arc.name, locale)}</h2><p className="mt-4 max-w-md leading-7 text-[var(--muted)]">{localize(arc.tagline, locale)}</p><Link className="button-primary mt-8" href={`/${locale}/products/${arc.slug}`}>{t.common.learnMore}<ArrowRight size={18}/></Link></div></section>
    <section className="shell py-16 md:py-24"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Four useful modes</p><h2 className="mt-4 text-4xl font-medium tracking-[-.06em]">Made to leave your hands and attention freer.</h2></div><div className="grid grid-cols-2 gap-px bg-[var(--line)]"><Feature icon={<Video/>} title="Capture" text="Photo and video fields appear only on configured camera series."/><Feature icon={<Languages/>} title="Translate" text="Connected through the app, Bluetooth and phone internet."/><Feature icon={<Headphones/>} title="Listen" text="Open-ear audio and music vary by selected series."/><Feature icon={<Map/>} title="Move" text="Find the right fit for rides, trips and everyday routes."/></div></div></section>
    <section className="border-y border-[var(--line)] bg-[#f0f3e9] py-16 md:py-24"><div className="shell grid gap-8 lg:grid-cols-[1fr_.95fr]"><div><p className="eyebrow">App connection</p><h2 className="mt-4 text-4xl font-medium tracking-[-.06em]">{t.home.appTitle}</h2><p className="mt-4 max-w-xl leading-7 text-[var(--muted)]">{t.home.appCopy}</p><Link className="button-secondary mt-8" href={`/${locale}/app`}>{t.common.app}<ArrowRight size={17}/></Link></div><div className="grid gap-px bg-[var(--line)] sm:grid-cols-3">{["Pair", "Personalize", "Keep connected"].map((step, index) => <div key={step} className="bg-[var(--paper)] p-6"><p className="text-sm font-bold text-[#7e9210]">0{index + 1}</p><h3 className="mt-16 font-bold">{step}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">A deliberate step in your phone-and-glasses connection.</p></div>)}</div></div></section>
    <section className="shell py-16 md:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Demo catalogue</p><h2 className="mt-4 text-4xl font-medium tracking-[-.06em]">Find your frame.</h2></div><Link href={`/${locale}/shop`} className="button-secondary">{t.common.viewAll}<ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-x-5 gap-y-12 sm:grid-cols-2 xl:grid-cols-3">{products.slice(0, 3).map((product) => <ProductCard product={product} locale={locale} key={product.id}/>)}</div></section>
    <section className="border-t border-[var(--line)] bg-[var(--dark)] py-16 text-white"><div className="shell grid gap-8 md:grid-cols-[1fr_.8fr]"><div><p className="eyebrow text-zinc-400">Newsletter</p><h2 className="mt-4 text-4xl font-medium tracking-[-.06em]">{t.home.subscribe}</h2><p className="mt-4 max-w-md leading-7 text-zinc-300">{t.home.subscribeCopy}</p></div><div className="bg-white p-6 text-[var(--ink)]"><DemoForm locale={locale} kind="newsletter"/></div></div></section>
  </>;
}
function Decision({ product, category, locale, image, number, detail }: { product: typeof products[number]; category: string; locale: Locale; image: string; number: string; detail: string }) { return <article className="grid gap-4 border-b border-[var(--line)] py-5 md:grid-cols-[1fr_240px_auto] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#81940e]"><span className="me-2 bg-[var(--lime)] px-1.5 py-1 text-[var(--ink)]">{number}</span>{category}</p><h2 className="mt-3 text-3xl font-medium tracking-[-.05em]">{localize(product.name, locale)}</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{localize(product.tagline, locale)}</p><p className="mt-3 text-xs text-[var(--muted)]">{detail}</p><div className="mt-2"><Price usd={product.usdPrice} locale={locale} compact/></div></div><Image src={image} alt={`Demo ${localize(product.name, locale)}`} width={500} height={280} className="aspect-[16/9] w-full object-cover" sizes="(max-width: 768px) 100vw, 240px"/><Link className="button-primary md:justify-self-end" href={`/${locale}/products/${product.slug}`}>{locale === "en" ? "Choose" : "Shop"}<ArrowRight size={17}/></Link></article>; }
function ExploreLink({ href, label }: { href: string; label: string }) { return <Link className="group border-t border-[var(--line)] py-4 hover:text-[#7b8e0c]" href={href}>{label}<ArrowRight className="float-end transition group-hover:translate-x-1" size={17}/></Link>; }
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="bg-[var(--paper)] p-6"><div className="text-[#7c8f10]">{icon}</div><h3 className="mt-14 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text}</p></div>; }
