"use server";
import { revalidatePath } from "next/cache";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { getDatabase } from "@/db/client";
import { customerTags, membershipTiers } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";
import { writeAuditLog } from "@/lib/admin/audit";
export type CustomerOperationState = { success: boolean; message: string }; export const initialCustomerOperationState: CustomerOperationState = { success: false, message: "" };
const tagSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(80), color: z.string().trim().max(24).optional() });
const tierSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(80), thresholdAmount: z.string().regex(/^\d+(\.\d{1,2})?$/), benefits: z.string().trim().max(4000).optional() });
async function audit(actor: string, action: string, type: string, id: string | undefined, path: string) { await writeAuditLog({ actorId: actor, action, resourceType: type, resourceId: id, result: "success" }); revalidatePath(path); }
export async function saveTagAction(_state: CustomerOperationState, fd: FormData): Promise<CustomerOperationState> { const actor = await requirePermission("customers.update"); const p = tagSchema.safeParse(Object.fromEntries(fd)); if (!p.success) return { success: false, message: p.error.issues[0]?.message ?? "标签信息不完整。" }; try { let id = p.data.id; if (id) await getDatabase().update(customerTags).set({ name: p.data.name, color: p.data.color || null }).where(eq(customerTags.id, id)); else { const [r] = await getDatabase().insert(customerTags).values({ name: p.data.name, color: p.data.color || null }).returning({ id: customerTags.id }); id = r?.id; } await audit(actor.id, `customers.tag.${p.data.id ? "update" : "create"}`, "customer_tag", id, "/admin/customer-tags"); return { success: true, message: "客户标签已保存。" }; } catch (e) { console.error(e); return { success: false, message: "保存失败，标签名称可能已重复。" }; } }
export async function saveTierAction(_state: CustomerOperationState, fd: FormData): Promise<CustomerOperationState> { const actor = await requirePermission("customers.update"); const p = tierSchema.safeParse(Object.fromEntries(fd)); if (!p.success) return { success: false, message: p.error.issues[0]?.message ?? "会员等级信息不完整。" }; try { let benefits: Record<string, unknown> = {}; if (p.data.benefits) benefits = JSON.parse(p.data.benefits) as Record<string, unknown>; let id = p.data.id; const values = { name: p.data.name, thresholdAmount: p.data.thresholdAmount, benefits, updatedAt: new Date() }; if (id) await getDatabase().update(membershipTiers).set(values).where(eq(membershipTiers.id, id)); else { const [r] = await getDatabase().insert(membershipTiers).values(values).returning({ id: membershipTiers.id }); id = r?.id; } await audit(actor.id, `customers.tier.${p.data.id ? "update" : "create"}`, "membership_tier", id, "/admin/memberships"); return { success: true, message: "会员等级已保存。" }; } catch (e) { console.error(e); return { success: false, message: "保存失败，权益必须是有效 JSON。" }; } }
