import { and, count, desc, eq, gte, ilike, lte, or } from "drizzle-orm";
import { DateRangeFilter } from "@/components/admin/date-range-filter";
import { TablePagination } from "@/components/admin/table-pagination";
import { getDatabase } from "@/db/client";
import { inventoryMovements, productSkus, products } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";
import { dateRangeQuery, getDateRange } from "@/lib/admin/date-range";
import { ADMIN_PAGE_SIZES, getAdminPagination } from "@/lib/admin/pagination";

type Search = { range?: string; from?: string; to?: string; page?: string; pageSize?: string; q?: string; type?: string };
const movementTypes = ["initial", "inbound", "outbound", "reservation", "release", "adjustment", "return"] as const;

export default async function InventoryLedgerPage({ searchParams }: { searchParams: Promise<Search> }) {
  await requirePermission("catalog.read");
  const input = await searchParams; const range = getDateRange(input); const { page, pageSize, offset } = getAdminPagination(input, 50); const q = input.q?.trim() ?? ""; const type = movementTypes.includes(input.type as (typeof movementTypes)[number]) ? input.type as (typeof movementTypes)[number] : undefined;
  const where = and(gte(inventoryMovements.createdAt, range.from), lte(inventoryMovements.createdAt, range.to), type ? eq(inventoryMovements.type, type) : undefined, q ? or(ilike(productSkus.sku, `%${q}%`), ilike(products.name, `%${q}%`)) : undefined);
  const db = getDatabase();
  const [{ total }] = await db.select({ total: count() }).from(inventoryMovements).innerJoin(productSkus, eq(inventoryMovements.skuId, productSkus.id)).innerJoin(products, eq(productSkus.productId, products.id)).where(where);
  const rows = await db.select({ id: inventoryMovements.id, type: inventoryMovements.type, delta: inventoryMovements.quantityDelta, note: inventoryMovements.note, referenceType: inventoryMovements.referenceType, referenceId: inventoryMovements.referenceId, createdAt: inventoryMovements.createdAt, sku: productSkus.sku, product: products.name }).from(inventoryMovements).innerJoin(productSkus, eq(inventoryMovements.skuId, productSkus.id)).innerJoin(products, eq(productSkus.productId, products.id)).where(where).orderBy(desc(inventoryMovements.createdAt)).limit(pageSize).offset(offset);
  const href = (nextPage: number) => `/admin/inventory-ledger?${new URLSearchParams({ ...dateRangeQuery(range), ...(q ? { q } : {}), ...(type ? { type } : {}), pageSize: String(pageSize), page: String(nextPage) })}`;
  return <div className="mx-auto max-w-[1560px] px-5 py-7 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#538a42]">商品</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-[-.04em]">库存流水</h1><p className="mt-2 text-sm text-black/55">每次后台调整和前台订单预留都会记录在此，支持按日期、类型和 SKU 查询。</p><form className="mt-6 rounded-2xl border border-black/10 bg-white p-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_160px_150px]"><input name="q" defaultValue={q} placeholder="商品或 SKU" className="rounded-xl border border-black/12 px-3 py-2.5"/><select name="type" defaultValue={type ?? ""} className="rounded-xl border border-black/12 bg-white px-3 py-2.5"><option value="">全部类型</option>{movementTypes.map((item) => <option key={item} value={item}>{item}</option>)}</select><label className="grid gap-1 text-xs font-semibold text-black/60">每页条数<select name="pageSize" defaultValue={pageSize} className="rounded-xl border border-black/12 bg-white px-3 py-2.5">{ADMIN_PAGE_SIZES.map((size) => <option key={size} value={size}>{size} 条</option>)}</select></label></div><DateRangeFilter range={range} className="mt-3"/><button className="mt-3 rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white">查询流水</button></form><section className="mt-5 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[#f5f7f4] text-xs uppercase tracking-wide text-black/52"><tr><th className="px-5 py-4">时间</th><th className="px-5 py-4">商品 / SKU</th><th className="px-5 py-4">类型</th><th className="px-5 py-4">变动</th><th className="px-5 py-4">关联</th><th className="px-5 py-4">备注</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-black/8"><td className="px-5 py-4 text-black/55">{row.createdAt.toLocaleString("zh-CN")}</td><td className="px-5 py-4"><p className="font-bold">{row.product}</p><p className="font-mono text-xs text-black/50">{row.sku}</p></td><td className="px-5 py-4">{row.type}</td><td className={`px-5 py-4 font-bold ${row.delta < 0 ? "text-[#b05a00]" : "text-[#3e752e]"}`}>{row.delta > 0 ? "+" : ""}{row.delta}</td><td className="px-5 py-4 text-xs text-black/55">{row.referenceType ?? "—"} {row.referenceId ?? ""}</td><td className="px-5 py-4 text-black/55">{row.note ?? "—"}</td></tr>) : <tr><td colSpan={6} className="px-5 py-16 text-center text-black/55">当前筛选条件下暂无库存流水。</td></tr>}</tbody></table></div><TablePagination page={page} pageSize={pageSize} total={Number(total)} href={href}/></section></div>;
}
