import Link from "next/link";
import { DateRangeFilter } from "@/components/admin/date-range-filter";
import { getDateRange } from "@/lib/admin/date-range";
import { getTrafficSummary } from "@/lib/analytics/traffic";
import { requirePermission } from "@/lib/admin/auth";

export default async function TrafficPage({ searchParams }: { searchParams: Promise<{ range?: string; from?: string; to?: string }> }) {
  await requirePermission("analytics.read");
  const range = getDateRange(await searchParams);
  const summary = await getTrafficSummary(range);
  const metrics = [["页面浏览", summary.pageViews], ["访问会话", summary.sessions], ["匿名访客", summary.visitors], ["商品浏览", summary.productViews], ["加入购物车", summary.carts], ["开始结账", summary.checkouts], ["创建订单", summary.orders]];
  return <main className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-bold">访问分析</h1><p className="mt-2 text-sm text-black/55">基于前台第一方真实访问事件；国家来自 Vercel 请求地区信息，明细数据每 60 秒更新缓存。</p></div><div className="flex gap-2"><Link href="/admin/analytics/visitors" className="rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white">查看访客明细</Link><Link href="/admin/analytics/paths" className="rounded-xl border border-black/15 bg-white px-4 py-2.5 text-sm font-bold">查看访问路径</Link></div></div><form className="mt-5 rounded-2xl border border-black/10 bg-white p-4"><DateRangeFilter range={range}/><button className="mt-3 rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white">更新分析</button></form><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-black/10 bg-white p-5"><p className="text-sm text-black/55">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></article>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="overflow-hidden rounded-2xl border border-black/10 bg-white"><h2 className="border-b border-black/8 p-5 font-serif text-2xl font-bold">热门页面</h2><table className="w-full text-left text-sm"><thead className="bg-[#f5f7f4]"><tr><th className="p-4">页面路径</th><th className="p-4">浏览量</th></tr></thead><tbody>{summary.paths.length ? summary.paths.map((row) => <tr key={row.path} className="border-t border-black/8"><td className="p-4 font-mono text-xs">{row.path || "/"}</td><td className="p-4">{row.views}</td></tr>) : <tr><td colSpan={2} className="p-12 text-center text-black/55">当前日期范围内暂无访问事件。</td></tr>}</tbody></table></section><section className="overflow-hidden rounded-2xl border border-black/10 bg-white"><h2 className="border-b border-black/8 p-5 font-serif text-2xl font-bold">访问国家 / 地区</h2><table className="w-full text-left text-sm"><thead className="bg-[#f5f7f4]"><tr><th className="p-4">国家 / 地区</th><th className="p-4">会话数</th></tr></thead><tbody>{summary.countries.length ? summary.countries.map((row) => <tr key={row.countryCode ?? "unknown"} className="border-t border-black/8"><td className="p-4"><strong>{row.countryName ?? "未知"}</strong><span className="ml-2 text-xs text-black/50">{row.countryCode ?? "—"}</span></td><td className="p-4">{row.sessions}</td></tr>) : <tr><td colSpan={2} className="p-12 text-center text-black/55">新版本上线后，国家与地区数据将从后续访问开始累积。</td></tr>}</tbody></table></section></div></main>;
}
