import Link from "next/link";
import { DateRangeFilter } from "@/components/admin/date-range-filter";
import { TablePagination } from "@/components/admin/table-pagination";
import type { DateRange } from "@/lib/admin/date-range";
import { ADMIN_PAGE_SIZES } from "@/lib/admin/pagination";

export type AfterSalesRow = { id: string; number: string; type: string; status: string; reason: string | null; requestedAmount: string | null; createdAt: Date; orderId: string; orderNumber: string; email: string | null };
type Props = { title: string; description: string; rows: AfterSalesRow[]; total: number; page: number; pageSize: number; range: DateRange; href: (page: number) => string; status?: string };

export function AfterSalesTable({ title, description, rows, total, page, pageSize, range, href, status }: Props) { return <div className="mx-auto max-w-[1560px] px-5 py-7 sm:px-8 lg:px-10"><div className="border-b border-black/10 pb-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#538a42]">经营</p><h1 className="mt-2 font-serif text-4xl font-bold">{title}</h1><p className="mt-2 text-sm text-black/55">{description}</p></div><form className="mt-6 rounded-2xl border border-black/10 bg-white p-4"><div className="flex flex-wrap gap-3"><label className="grid gap-1 text-xs font-semibold text-black/60">处理状态<input name="status" defaultValue={status ?? ""} placeholder="例如 pending" className="rounded-xl border border-black/12 px-3 py-2.5"/></label><label className="grid gap-1 text-xs font-semibold text-black/60">每页条数<select name="pageSize" defaultValue={pageSize} className="rounded-xl border border-black/12 bg-white px-3 py-2.5">{ADMIN_PAGE_SIZES.map((size) => <option key={size} value={size}>{size} 条</option>)}</select></label></div><DateRangeFilter range={range} className="mt-3"/><button className="mt-3 rounded-xl bg-[#17231c] px-4 py-2.5 text-sm font-bold text-white">查询售后</button></form><section className="mt-5 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#f5f7f4] text-xs uppercase tracking-wide text-black/52"><tr><th className="px-5 py-4">申请号</th><th className="px-5 py-4">订单 / 客户</th><th className="px-5 py-4">类型</th><th className="px-5 py-4">状态</th><th className="px-5 py-4">申请金额</th><th className="px-5 py-4">原因</th><th className="px-5 py-4">时间</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-black/8"><td className="px-5 py-4 font-mono text-xs">{row.number}</td><td className="px-5 py-4"><Link href={`/admin/orders/${row.orderId}`} className="font-bold text-[#477b38]">{row.orderNumber}</Link><p className="mt-1 text-xs text-black/50">{row.email ?? "—"}</p></td><td className="px-5 py-4">{row.type}</td><td className="px-5 py-4">{row.status}</td><td className="px-5 py-4">{row.requestedAmount ? `USD ${row.requestedAmount}` : "—"}</td><td className="max-w-60 truncate px-5 py-4 text-black/55">{row.reason ?? "—"}</td><td className="px-5 py-4 text-black/55">{row.createdAt.toLocaleString("zh-CN")}</td></tr>) : <tr><td colSpan={7} className="px-5 py-14 text-center text-black/55">当前筛选条件下暂无售后申请。</td></tr>}</tbody></table></div><TablePagination page={page} pageSize={pageSize} total={total} href={href}/></section></div>; }
