import { and, count, desc, eq, gte, lte } from "drizzle-orm";
import { getDatabase } from "@/db/client";
import { aftersalesRequests, customers, orders } from "@/db/schema";
import { requirePermission } from "@/lib/admin/auth";
import { dateRangeQuery, getDateRange } from "@/lib/admin/date-range";
import { getAdminPagination } from "@/lib/admin/pagination";
import { AfterSalesTable } from "../aftersales-table";

type Search = { range?: string; from?: string; to?: string; page?: string; pageSize?: string; status?: string };
const aftersalesStatuses = ["requested", "approved", "rejected", "received", "refunding", "refunded", "closed"] as const;
export default async function TicketsPage({ searchParams }: { searchParams: Promise<Search> }) { await requirePermission("orders.read"); const input = await searchParams; const range = getDateRange(input); const { page, pageSize, offset } = getAdminPagination(input, 25); const status = aftersalesStatuses.includes(input.status as (typeof aftersalesStatuses)[number]) ? input.status as (typeof aftersalesStatuses)[number] : undefined; const where = and(gte(aftersalesRequests.createdAt, range.from), lte(aftersalesRequests.createdAt, range.to), status ? eq(aftersalesRequests.status, status) : undefined); const db = getDatabase(); const [{ total }] = await db.select({ total: count() }).from(aftersalesRequests).where(where); const rows = await db.select({ id: aftersalesRequests.id, number: aftersalesRequests.requestNumber, type: aftersalesRequests.type, status: aftersalesRequests.status, reason: aftersalesRequests.reason, requestedAmount: aftersalesRequests.requestedAmount, createdAt: aftersalesRequests.createdAt, orderId: orders.id, orderNumber: orders.orderNumber, email: customers.email }).from(aftersalesRequests).innerJoin(orders, eq(aftersalesRequests.orderId, orders.id)).leftJoin(customers, eq(aftersalesRequests.customerId, customers.id)).where(where).orderBy(desc(aftersalesRequests.createdAt)).limit(pageSize).offset(offset); const href = (next: number) => `/admin/tickets?${new URLSearchParams({ ...dateRangeQuery(range), ...(status ? { status } : {}), pageSize: String(pageSize), page: String(next) })}`; return <AfterSalesTable title="售后工单" description="客户售后请求、处理状态和关联订单。退换货申请会自动归集到该列表。" rows={rows} total={Number(total)} page={page} pageSize={pageSize} range={range} href={href} status={status}/>; }
