// Generated by tools/import_product_assets.py from the supplied source folders.
// Do not edit file paths by hand; rerun the importer when source assets change.
export const importedProductAssets = {
  "g06-l": {
    "heroImage": "/images/products/g06-l/black-01.webp",
    "colors": [
      {
        "id": "g06-l-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/g06-l/black-01.webp",
          "/images/products/g06-l/black-02.webp",
          "/images/products/g06-l/black-03.webp",
          "/images/products/g06-l/black-04.webp",
          "/images/products/g06-l/black-05.webp",
          "/images/products/g06-l/black-06.webp",
          "/images/products/g06-l/black-07.webp",
          "/images/products/g06-l/black-08.webp",
          "/images/products/g06-l/black-09.webp",
          "/images/products/g06-l/black-10.webp",
          "/images/products/g06-l/black-11.webp",
          "/images/products/g06-l/black-12.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/g06-l/detail-01.webp",
      "/images/products/g06-l/detail-02.webp",
      "/images/products/g06-l/detail-03.webp",
      "/images/products/g06-l/detail-04.webp",
      "/images/products/g06-l/detail-05.webp",
      "/images/products/g06-l/detail-06.webp",
      "/images/products/g06-l/detail-07.webp",
      "/images/products/g06-l/detail-08.webp",
      "/images/products/g06-l/detail-09.webp",
      "/images/products/g06-l/detail-10.webp",
      "/images/products/g06-l/detail-11.webp",
      "/images/products/g06-l/detail-12.webp",
      "/images/products/g06-l/detail-13.webp",
      "/images/products/g06-l/detail-14.webp",
      "/images/products/g06-l/detail-15.webp",
      "/images/products/g06-l/detail-16.webp",
      "/images/products/g06-l/detail-17.webp",
      "/images/products/g06-l/detail-18.webp"
    ]
  },
  "g06-t": {
    "heroImage": "/images/products/g06-t/black-01.webp",
    "colors": [
      {
        "id": "g06-t-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/g06-t/black-01.webp",
          "/images/products/g06-t/black-02.webp",
          "/images/products/g06-t/black-03.webp",
          "/images/products/g06-t/black-04.webp",
          "/images/products/g06-t/black-05.webp",
          "/images/products/g06-t/black-06.webp",
          "/images/products/g06-t/black-07.webp",
          "/images/products/g06-t/black-08.webp",
          "/images/products/g06-t/black-09.webp",
          "/images/products/g06-t/black-10.webp",
          "/images/products/g06-t/black-11.webp",
          "/images/products/g06-t/black-12.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/g06-t/detail-01.webp",
      "/images/products/g06-t/detail-02.webp",
      "/images/products/g06-t/detail-03.webp",
      "/images/products/g06-t/detail-04.webp",
      "/images/products/g06-t/detail-05.webp",
      "/images/products/g06-t/detail-06.webp",
      "/images/products/g06-t/detail-07.webp",
      "/images/products/g06-t/detail-08.webp",
      "/images/products/g06-t/detail-09.webp",
      "/images/products/g06-t/detail-10.webp",
      "/images/products/g06-t/detail-11.webp",
      "/images/products/g06-t/detail-12.webp",
      "/images/products/g06-t/detail-13.webp",
      "/images/products/g06-t/detail-14.webp",
      "/images/products/g06-t/detail-15.webp",
      "/images/products/g06-t/detail-16.webp",
      "/images/products/g06-t/detail-17.webp"
    ]
  },
  "g200-sport-audio-glasses": {
    "heroImage": "/images/products/g200-sport-audio-glasses/blue-mirror-lens-01.webp",
    "colors": [
      {
        "id": "g200-sport-audio-glasses-blue-mirror-lens",
        "name": "Blue mirror lens",
        "hex": "#21ace5",
        "images": [
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-01.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-02.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-03.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-04.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-05.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-06.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-07.webp",
          "/images/products/g200-sport-audio-glasses/blue-mirror-lens-08.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/g200-sport-audio-glasses/detail-01.webp",
      "/images/products/g200-sport-audio-glasses/detail-02.webp",
      "/images/products/g200-sport-audio-glasses/detail-03.webp",
      "/images/products/g200-sport-audio-glasses/detail-04.webp",
      "/images/products/g200-sport-audio-glasses/detail-05.webp",
      "/images/products/g200-sport-audio-glasses/detail-06.webp",
      "/images/products/g200-sport-audio-glasses/detail-07.webp",
      "/images/products/g200-sport-audio-glasses/detail-08.webp",
      "/images/products/g200-sport-audio-glasses/detail-09.webp",
      "/images/products/g200-sport-audio-glasses/detail-10.webp",
      "/images/products/g200-sport-audio-glasses/detail-11.webp"
    ]
  },
  "gl1": {
    "heroImage": "/images/products/gl1/steel-grey-01.webp",
    "colors": [
      {
        "id": "gl1-steel-grey",
        "name": "Steel grey",
        "hex": "#8d9192",
        "images": [
          "/images/products/gl1/steel-grey-01.webp",
          "/images/products/gl1/steel-grey-02.webp",
          "/images/products/gl1/steel-grey-03.webp",
          "/images/products/gl1/steel-grey-04.webp",
          "/images/products/gl1/steel-grey-05.webp",
          "/images/products/gl1/steel-grey-06.webp"
        ],
        "available": true
      },
      {
        "id": "gl1-champagne-gold",
        "name": "Champagne gold",
        "hex": "#c9aa7e",
        "images": [
          "/images/products/gl1/champagne-gold-01.webp",
          "/images/products/gl1/champagne-gold-02.webp",
          "/images/products/gl1/champagne-gold-03.webp",
          "/images/products/gl1/champagne-gold-04.webp",
          "/images/products/gl1/champagne-gold-05.webp",
          "/images/products/gl1/champagne-gold-06.webp"
        ],
        "available": true
      },
      {
        "id": "gl1-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl1/black-01.webp",
          "/images/products/gl1/black-02.webp",
          "/images/products/gl1/black-03.webp",
          "/images/products/gl1/black-04.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl1/detail-01.webp",
      "/images/products/gl1/detail-02.webp",
      "/images/products/gl1/detail-03.webp",
      "/images/products/gl1/detail-04.webp",
      "/images/products/gl1/detail-05.webp",
      "/images/products/gl1/detail-06.webp",
      "/images/products/gl1/detail-07.webp",
      "/images/products/gl1/detail-08.webp",
      "/images/products/gl1/detail-09.webp",
      "/images/products/gl1/detail-10.webp",
      "/images/products/gl1/detail-11.webp",
      "/images/products/gl1/detail-12.webp"
    ]
  },
  "gl6": {
    "heroImage": "/images/products/gl6/black-01.webp",
    "colors": [
      {
        "id": "gl6-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl6/black-01.webp",
          "/images/products/gl6/black-02.webp",
          "/images/products/gl6/black-03.webp",
          "/images/products/gl6/black-04.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl6/detail-01.webp",
      "/images/products/gl6/detail-02.webp",
      "/images/products/gl6/detail-03.webp",
      "/images/products/gl6/detail-04.webp",
      "/images/products/gl6/detail-05.webp",
      "/images/products/gl6/detail-06.webp",
      "/images/products/gl6/detail-07.webp",
      "/images/products/gl6/detail-08.webp",
      "/images/products/gl6/detail-09.webp",
      "/images/products/gl6/detail-10.webp",
      "/images/products/gl6/detail-11.webp",
      "/images/products/gl6/detail-12.webp",
      "/images/products/gl6/detail-13.webp"
    ]
  },
  "gl7": {
    "heroImage": "/images/products/gl7/black-01.webp",
    "colors": [
      {
        "id": "gl7-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl7/black-01.webp",
          "/images/products/gl7/black-02.webp",
          "/images/products/gl7/black-03.webp",
          "/images/products/gl7/black-04.webp",
          "/images/products/gl7/black-05.webp",
          "/images/products/gl7/black-06.webp",
          "/images/products/gl7/black-07.webp",
          "/images/products/gl7/black-08.webp",
          "/images/products/gl7/black-09.webp",
          "/images/products/gl7/black-10.webp",
          "/images/products/gl7/black-11.webp",
          "/images/products/gl7/black-12.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl7/detail-01.webp",
      "/images/products/gl7/detail-02.webp",
      "/images/products/gl7/detail-03.webp",
      "/images/products/gl7/detail-04.webp",
      "/images/products/gl7/detail-05.webp",
      "/images/products/gl7/detail-06.webp",
      "/images/products/gl7/detail-07.webp",
      "/images/products/gl7/detail-08.webp",
      "/images/products/gl7/detail-09.webp",
      "/images/products/gl7/detail-10.webp",
      "/images/products/gl7/detail-11.webp",
      "/images/products/gl7/detail-12.webp",
      "/images/products/gl7/detail-13.webp",
      "/images/products/gl7/detail-14.webp"
    ]
  },
  "gl8": {
    "heroImage": "/images/products/gl8/black-01.webp",
    "colors": [
      {
        "id": "gl8-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl8/black-01.webp",
          "/images/products/gl8/black-02.webp",
          "/images/products/gl8/black-03.webp",
          "/images/products/gl8/black-04.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl8/detail-01.webp",
      "/images/products/gl8/detail-02.webp",
      "/images/products/gl8/detail-03.webp",
      "/images/products/gl8/detail-04.webp",
      "/images/products/gl8/detail-05.webp",
      "/images/products/gl8/detail-06.webp",
      "/images/products/gl8/detail-07.webp",
      "/images/products/gl8/detail-08.webp",
      "/images/products/gl8/detail-09.webp",
      "/images/products/gl8/detail-10.webp",
      "/images/products/gl8/detail-11.webp",
      "/images/products/gl8/detail-12.webp",
      "/images/products/gl8/detail-13.webp"
    ]
  },
  "gl12-8": {
    "heroImage": "/images/products/gl12-8/black-01.webp",
    "colors": [
      {
        "id": "gl12-8-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl12-8/black-01.webp",
          "/images/products/gl12-8/black-02.webp",
          "/images/products/gl12-8/black-03.webp",
          "/images/products/gl12-8/black-04.webp",
          "/images/products/gl12-8/black-05.webp",
          "/images/products/gl12-8/black-06.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl12-8/detail-01.webp",
      "/images/products/gl12-8/detail-02.webp",
      "/images/products/gl12-8/detail-03.webp",
      "/images/products/gl12-8/detail-04.webp",
      "/images/products/gl12-8/detail-05.webp",
      "/images/products/gl12-8/detail-06.webp",
      "/images/products/gl12-8/detail-07.webp",
      "/images/products/gl12-8/detail-08.webp",
      "/images/products/gl12-8/detail-09.webp",
      "/images/products/gl12-8/detail-10.webp",
      "/images/products/gl12-8/detail-11.webp",
      "/images/products/gl12-8/detail-12.webp",
      "/images/products/gl12-8/detail-13.webp"
    ]
  },
  "gl12-9": {
    "heroImage": "/images/products/gl12-9/black-01.webp",
    "colors": [
      {
        "id": "gl12-9-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl12-9/black-01.webp",
          "/images/products/gl12-9/black-02.webp",
          "/images/products/gl12-9/black-03.webp",
          "/images/products/gl12-9/black-04.webp",
          "/images/products/gl12-9/black-05.webp",
          "/images/products/gl12-9/black-06.webp",
          "/images/products/gl12-9/black-07.webp",
          "/images/products/gl12-9/black-08.webp",
          "/images/products/gl12-9/black-09.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl12-9/detail-01.webp",
      "/images/products/gl12-9/detail-02.webp",
      "/images/products/gl12-9/detail-03.webp",
      "/images/products/gl12-9/detail-04.webp",
      "/images/products/gl12-9/detail-05.webp"
    ]
  },
  "gl15-1": {
    "heroImage": "/images/products/gl15-1/black-01.webp",
    "colors": [
      {
        "id": "gl15-1-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl15-1/black-01.webp",
          "/images/products/gl15-1/black-02.webp",
          "/images/products/gl15-1/black-03.webp",
          "/images/products/gl15-1/black-04.webp",
          "/images/products/gl15-1/black-05.webp",
          "/images/products/gl15-1/black-06.webp",
          "/images/products/gl15-1/black-07.webp",
          "/images/products/gl15-1/black-08.webp",
          "/images/products/gl15-1/black-09.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl15-1/detail-01.webp",
      "/images/products/gl15-1/detail-02.webp",
      "/images/products/gl15-1/detail-03.webp",
      "/images/products/gl15-1/detail-04.webp",
      "/images/products/gl15-1/detail-05.webp",
      "/images/products/gl15-1/detail-06.webp",
      "/images/products/gl15-1/detail-07.webp",
      "/images/products/gl15-1/detail-08.webp",
      "/images/products/gl15-1/detail-09.webp",
      "/images/products/gl15-1/detail-10.webp",
      "/images/products/gl15-1/detail-11.webp"
    ]
  },
  "gl15-2": {
    "heroImage": "/images/products/gl15-2/black-01.webp",
    "colors": [
      {
        "id": "gl15-2-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl15-2/black-01.webp",
          "/images/products/gl15-2/black-02.webp",
          "/images/products/gl15-2/black-03.webp",
          "/images/products/gl15-2/black-04.webp",
          "/images/products/gl15-2/black-05.webp",
          "/images/products/gl15-2/black-06.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl15-2/detail-01.webp",
      "/images/products/gl15-2/detail-02.webp",
      "/images/products/gl15-2/detail-03.webp",
      "/images/products/gl15-2/detail-04.webp",
      "/images/products/gl15-2/detail-05.webp"
    ]
  },
  "gl16-3": {
    "heroImage": "/images/products/gl16-3/black-01.webp",
    "colors": [
      {
        "id": "gl16-3-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/gl16-3/black-01.webp",
          "/images/products/gl16-3/black-02.webp",
          "/images/products/gl16-3/black-03.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/gl16-3/detail-01.webp",
      "/images/products/gl16-3/detail-02.webp",
      "/images/products/gl16-3/detail-03.webp",
      "/images/products/gl16-3/detail-04.webp",
      "/images/products/gl16-3/detail-05.webp",
      "/images/products/gl16-3/detail-06.webp",
      "/images/products/gl16-3/detail-07.webp",
      "/images/products/gl16-3/detail-08.webp",
      "/images/products/gl16-3/detail-09.webp"
    ]
  },
  "v03-pro": {
    "heroImage": "/images/products/v03-pro/khaki-01.webp",
    "colors": [
      {
        "id": "v03-pro-khaki",
        "name": "Khaki",
        "hex": "#a58c70",
        "images": [
          "/images/products/v03-pro/khaki-01.webp",
          "/images/products/v03-pro/khaki-02.webp",
          "/images/products/v03-pro/khaki-03.webp",
          "/images/products/v03-pro/khaki-04.webp",
          "/images/products/v03-pro/khaki-05.webp",
          "/images/products/v03-pro/khaki-06.webp",
          "/images/products/v03-pro/khaki-07.webp",
          "/images/products/v03-pro/khaki-08.webp",
          "/images/products/v03-pro/khaki-09.webp",
          "/images/products/v03-pro/khaki-10.webp",
          "/images/products/v03-pro/khaki-11.webp",
          "/images/products/v03-pro/khaki-12.webp",
          "/images/products/v03-pro/khaki-13.webp",
          "/images/products/v03-pro/khaki-14.webp",
          "/images/products/v03-pro/khaki-15.webp",
          "/images/products/v03-pro/khaki-16.webp",
          "/images/products/v03-pro/khaki-17.webp",
          "/images/products/v03-pro/khaki-18.webp",
          "/images/products/v03-pro/khaki-19.webp",
          "/images/products/v03-pro/khaki-20.webp",
          "/images/products/v03-pro/khaki-21.webp",
          "/images/products/v03-pro/khaki-22.webp",
          "/images/products/v03-pro/khaki-23.webp",
          "/images/products/v03-pro/khaki-24.webp"
        ],
        "available": true
      },
      {
        "id": "v03-pro-orange",
        "name": "Orange",
        "hex": "#d86b31",
        "images": [
          "/images/products/v03-pro/orange-01.webp",
          "/images/products/v03-pro/orange-02.webp",
          "/images/products/v03-pro/orange-03.webp",
          "/images/products/v03-pro/orange-04.webp",
          "/images/products/v03-pro/orange-05.webp",
          "/images/products/v03-pro/orange-06.webp",
          "/images/products/v03-pro/orange-07.webp",
          "/images/products/v03-pro/orange-08.webp",
          "/images/products/v03-pro/orange-09.webp",
          "/images/products/v03-pro/orange-10.webp",
          "/images/products/v03-pro/orange-11.webp",
          "/images/products/v03-pro/orange-12.webp",
          "/images/products/v03-pro/orange-13.webp",
          "/images/products/v03-pro/orange-14.webp",
          "/images/products/v03-pro/orange-15.webp",
          "/images/products/v03-pro/orange-16.webp",
          "/images/products/v03-pro/orange-17.webp",
          "/images/products/v03-pro/orange-18.webp",
          "/images/products/v03-pro/orange-19.webp",
          "/images/products/v03-pro/orange-20.webp",
          "/images/products/v03-pro/orange-21.webp",
          "/images/products/v03-pro/orange-22.webp",
          "/images/products/v03-pro/orange-23.webp",
          "/images/products/v03-pro/orange-24.webp"
        ],
        "available": true
      },
      {
        "id": "v03-pro-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/v03-pro/black-01.webp",
          "/images/products/v03-pro/black-02.webp",
          "/images/products/v03-pro/black-03.webp",
          "/images/products/v03-pro/black-04.webp",
          "/images/products/v03-pro/black-05.webp",
          "/images/products/v03-pro/black-06.webp",
          "/images/products/v03-pro/black-07.webp",
          "/images/products/v03-pro/black-08.webp",
          "/images/products/v03-pro/black-09.webp",
          "/images/products/v03-pro/black-10.webp",
          "/images/products/v03-pro/black-11.webp",
          "/images/products/v03-pro/black-12.webp",
          "/images/products/v03-pro/black-13.webp",
          "/images/products/v03-pro/black-14.webp",
          "/images/products/v03-pro/black-15.webp",
          "/images/products/v03-pro/black-16.webp",
          "/images/products/v03-pro/black-17.webp",
          "/images/products/v03-pro/black-18.webp",
          "/images/products/v03-pro/black-19.webp",
          "/images/products/v03-pro/black-20.webp",
          "/images/products/v03-pro/black-21.webp",
          "/images/products/v03-pro/black-22.webp",
          "/images/products/v03-pro/black-23.webp",
          "/images/products/v03-pro/black-24.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/v03-pro/detail-01.webp",
      "/images/products/v03-pro/detail-02.webp",
      "/images/products/v03-pro/detail-03.webp",
      "/images/products/v03-pro/detail-04.webp",
      "/images/products/v03-pro/detail-05.webp",
      "/images/products/v03-pro/detail-06.webp",
      "/images/products/v03-pro/detail-07.webp",
      "/images/products/v03-pro/detail-08.webp",
      "/images/products/v03-pro/detail-09.webp",
      "/images/products/v03-pro/detail-10.webp",
      "/images/products/v03-pro/detail-11.webp",
      "/images/products/v03-pro/detail-12.webp",
      "/images/products/v03-pro/detail-13.webp",
      "/images/products/v03-pro/detail-14.webp",
      "/images/products/v03-pro/detail-15.webp",
      "/images/products/v03-pro/detail-16.webp",
      "/images/products/v03-pro/detail-17.webp",
      "/images/products/v03-pro/detail-18.webp",
      "/images/products/v03-pro/detail-19.webp"
    ]
  },
  "v03-t5": {
    "heroImage": "/images/products/v03-t5/sunglasses-01.webp",
    "colors": [
      {
        "id": "v03-t5-sunglasses",
        "name": "Sunglasses",
        "hex": "#202225",
        "images": [
          "/images/products/v03-t5/sunglasses-01.webp",
          "/images/products/v03-t5/sunglasses-02.webp",
          "/images/products/v03-t5/sunglasses-03.webp",
          "/images/products/v03-t5/sunglasses-04.webp",
          "/images/products/v03-t5/sunglasses-05.webp",
          "/images/products/v03-t5/sunglasses-06.webp"
        ],
        "available": true
      },
      {
        "id": "v03-t5-blue-light",
        "name": "Blue-light",
        "hex": "#b8d7e9",
        "images": [
          "/images/products/v03-t5/blue-light-01.webp",
          "/images/products/v03-t5/blue-light-02.webp",
          "/images/products/v03-t5/blue-light-03.webp",
          "/images/products/v03-t5/blue-light-04.webp",
          "/images/products/v03-t5/blue-light-05.webp",
          "/images/products/v03-t5/blue-light-06.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/v03-t5/detail-01.webp",
      "/images/products/v03-t5/detail-02.webp",
      "/images/products/v03-t5/detail-03.webp",
      "/images/products/v03-t5/detail-04.webp",
      "/images/products/v03-t5/detail-05.webp",
      "/images/products/v03-t5/detail-06.webp",
      "/images/products/v03-t5/detail-07.webp",
      "/images/products/v03-t5/detail-08.webp",
      "/images/products/v03-t5/detail-09.webp",
      "/images/products/v03-t5/detail-10.webp",
      "/images/products/v03-t5/detail-11.webp",
      "/images/products/v03-t5/detail-12.webp",
      "/images/products/v03-t5/detail-13.webp",
      "/images/products/v03-t5/detail-14.webp",
      "/images/products/v03-t5/detail-15.webp",
      "/images/products/v03-t5/detail-16.webp"
    ]
  },
  "v03-t6": {
    "heroImage": "/images/products/v03-t6/sunglasses-01.webp",
    "colors": [
      {
        "id": "v03-t6-sunglasses",
        "name": "Sunglasses",
        "hex": "#202225",
        "images": [
          "/images/products/v03-t6/sunglasses-01.webp",
          "/images/products/v03-t6/sunglasses-02.webp",
          "/images/products/v03-t6/sunglasses-03.webp",
          "/images/products/v03-t6/sunglasses-04.webp",
          "/images/products/v03-t6/sunglasses-05.webp",
          "/images/products/v03-t6/sunglasses-06.webp"
        ],
        "available": true
      },
      {
        "id": "v03-t6-blue-light",
        "name": "Blue-light",
        "hex": "#b8d7e9",
        "images": [
          "/images/products/v03-t6/blue-light-01.webp",
          "/images/products/v03-t6/blue-light-02.webp",
          "/images/products/v03-t6/blue-light-03.webp",
          "/images/products/v03-t6/blue-light-04.webp",
          "/images/products/v03-t6/blue-light-05.webp",
          "/images/products/v03-t6/blue-light-06.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/v03-t6/detail-01.webp",
      "/images/products/v03-t6/detail-02.webp",
      "/images/products/v03-t6/detail-03.webp",
      "/images/products/v03-t6/detail-04.webp",
      "/images/products/v03-t6/detail-05.webp",
      "/images/products/v03-t6/detail-06.webp",
      "/images/products/v03-t6/detail-07.webp",
      "/images/products/v03-t6/detail-08.webp",
      "/images/products/v03-t6/detail-09.webp",
      "/images/products/v03-t6/detail-10.webp",
      "/images/products/v03-t6/detail-11.webp",
      "/images/products/v03-t6/detail-12.webp"
    ]
  },
  "v03-t8": {
    "heroImage": "/images/products/v03-t8/black-01.webp",
    "colors": [
      {
        "id": "v03-t8-black",
        "name": "Black",
        "hex": "#202225",
        "images": [
          "/images/products/v03-t8/black-01.webp",
          "/images/products/v03-t8/black-02.webp",
          "/images/products/v03-t8/black-03.webp",
          "/images/products/v03-t8/black-04.webp",
          "/images/products/v03-t8/black-05.webp",
          "/images/products/v03-t8/black-06.webp"
        ],
        "available": true
      }
    ],
    "detailImages": [
      "/images/products/v03-t8/detail-01.webp",
      "/images/products/v03-t8/detail-02.webp",
      "/images/products/v03-t8/detail-03.webp",
      "/images/products/v03-t8/detail-04.webp",
      "/images/products/v03-t8/detail-05.webp",
      "/images/products/v03-t8/detail-06.webp",
      "/images/products/v03-t8/detail-07.webp",
      "/images/products/v03-t8/detail-08.webp",
      "/images/products/v03-t8/detail-09.webp",
      "/images/products/v03-t8/detail-10.webp",
      "/images/products/v03-t8/detail-11.webp",
      "/images/products/v03-t8/detail-12.webp",
      "/images/products/v03-t8/detail-13.webp"
    ]
  }
} as const;
